In [0]:
# 

# !pip install -U --target=/usr/local/lib/python3.6/dist-packages git+https://github.com/pytorch/botorch.git

# !pip install -U -q torch==1.2.0 torchvision

# !pip install -U scikit-learn
# !pip install -U --target=/usr/local/lib/python3.6/dist-packages git+https://github.com/anhhuyalex/Ax.git
  
!pip install -U --target=/usr/local/lib/python3.6/dist-packages git+https://github.com/anhhuyalex/Ax.git
  
%cd /content
# %cd /usr/local/lib/python3.6/dist-packages
!rm -rf botorch
%cd /content
!git clone https://github.com/pytorch/botorch.git
%cd botorch
!pip install .



/content
/content
Cloning into 'botorch'...
remote: Enumerating objects: 230, done.
remote: Counting objects: 100% (230/230), done.
remote: Compressing objects: 100% (158/158), done.
remote: Total 5926 (delta 87), reused 112 (delta 34), pack-reused 5696
Receiving objects: 100% (5926/5926), 10.52 MiB | 24.92 MiB/s, done.
Resolving deltas: 100% (3785/3785), done.
/content/botorch
Processing /content/botorch
  Created wheel for botorch: filename=botorch-0.1.3-cp36-none-any.whl size=175126 sha256=5907262eefb04ac8c2534ba5e4c2ec0bf6c7be3e82f2d23febe20b6160f991af
  Stored in directory: /tmp/pip-ephem-wheel-cache-cr81hh31/wheels/d8/0e/3f/502176509633fec729eabc1a42e465b3603faf0c30b4782f33
Successfully built botorch
  Found existing installation: botorch 0.1.3
    Uninstalling botorch-0.1.3:
      Successfully uninstalled botorch-0.1.3


  Cloning https://github.com/pytorch/botorch.git to /tmp/pip-req-build-9kwtgry5
  Running command git clone -q https://github.com/pytorch/botorch.git /tmp/pip-req-build-9kwtgry5
  Using cached https://files.pythonhosted.org/packages/30/57/d5cceb0799c06733eefce80c395459f28970ebb9e896846ce96ab579a3f1/torch-1.2.0-cp36-cp36m-manylinux1_x86_64.whl
  Using cached https://files.pythonhosted.org/packages/29/50/a552a5aff252ae915f522e44642bb49a7b7b31677f9580cfd11bcc869976/scipy-1.3.1-cp36-cp36m-manylinux1_x86_64.whl
  Using cached https://files.pythonhosted.org/packages/75/92/57179ed45307ec6179e344231c47da7f3f3da9e2eee5c8ab506bd279ce4e/numpy-1.17.1-cp36-cp36m-manylinux1_x86_64.whl
  Created wheel for botorch: filename=botorch-0.1.3-cp36-none-any.whl size=175126 sha256=154fde2c7ac78b7be391d0b23e120d695155142afdc5c7a9e7b725be7ad598f5
  Stored in directory: /tmp/pip-ephem-wheel-cache-my6avjjg/wheels/82/70/31/16688bea51fa7ff1a0100a484854a6c2a9663fde3055aa478a
Successfully built botorch
ERROR: google

In [5]:

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [6]:
%cd /content/drive/My\ Drive/Year\ 4\:\ Synthesis/NS162\:\ Statistical\ Mechanics/Renormalization\ Research\ Project/renormalization/supervised_convnet/t_2.269/3x3
!rm -rf botorch

/content/drive/My Drive/Year 4: Synthesis/NS162: Statistical Mechanics/Renormalization Research Project/renormalization/supervised_convnet/t_2.269/3x3


In [0]:
import torch
import numpy as np

from ax import RangeParameter, ParameterType
from ax.plot.contour import plot_contour
from ax.plot.trace import optimization_trace_single_method
from ax.service.managed_loop import optimize
from ax.utils.notebook.plotting import render, init_notebook_plotting

import sys
import time
sys.path.insert(0, "../../")
import supervised_convnet
import train, frozen

/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning:

Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.

/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning:

Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.

/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning:

Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.

/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning:

Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '

Uncorrelated [[ 1  1  1 -1 -1 -1  1 -1 -1]
 [ 1  1  1 -1 -1 -1 -1 -1 -1]
 [ 1  1  1 -1  1  1  1  1  1]
 [ 1  1 -1  1 -1 -1 -1 -1 -1]
 [ 1  1 -1  1 -1 -1 -1 -1 -1]
 [ 1  1  1  1 -1 -1 -1 -1  1]
 [ 1  1 -1 -1 -1 -1  1  1  1]
 [ 1 -1 -1 -1 -1 -1  1  1  1]
 [ 1  1  1 -1 -1 -1  1  1 -1]]
Correlated [[ 1  1 -1  1 -1 -1 -1 -1  1]
 [ 1  1 -1 -1 -1 -1 -1 -1 -1]
 [ 1  1 -1 -1 -1  1  1  1  1]
 [-1 -1 -1 -1 -1 -1  1  1  1]
 [ 1 -1 -1 -1 -1  1  1  1  1]
 [-1 -1 -1 -1 -1  1  1  1  1]
 [-1 -1 -1 -1 -1  1  1 -1 -1]
 [-1 -1 -1 -1 -1 -1  1  1  1]
 [-1 -1  1 -1 -1 -1 -1 -1  1]]


In [0]:
num_hidden_layers = 1
out_channels = 1
weight = 0.02

def train_evaluate(parameterization):
    # parameters
    batch_size = parameterization["batch_size"]
    train_size = parameterization["train_size"]
    n_epochs = parameterization["n_epochs"]
    lr = parameterization["lr"]
    weight_decay = parameterization["weight_decay"]
    betas0 = parameterization["betas0"]
    hidden_size = 10


    model = supervised_convnet.SupervisedConvNet(filter_size = 3, square_size = 3, \
            hidden_size = hidden_size, out_channels = out_channels,
            first_activation = "tanh", activation_func = "relu",
            num_hidden_layers = num_hidden_layers)
    tic = time.time()
    accuracy = train.trainer(model = model, batch_size = batch_size, train_size = train_size, n_epochs = n_epochs, lr = lr,
                weight_decay = weight_decay,
                betas0 = 1-betas0, betas1 = 0.99)[0]
    toc = time.time()
    return accuracy

best_parameters, best_values, experiment, model = optimize(
    parameters=[
        {
          "name": "batch_size",
          "type": "range",
          "bounds": [1, 5000],
          "value_type": "int"
        },
        {
          "name": "train_size",
          "type": "range",
          "bounds": [100, 5000],
          "value_type": "int"
        },
        {
          "name": "n_epochs",
          "type": "range",
          "bounds": [50, 250],
          "value_type": "int"
        },
        {
          "name": "lr",
          "type": "range",
          "bounds": [1e-4, 1],
          "value_type": "float",
          "log_scale": True
        },
        {
          "name": "weight_decay",
          "type": "range",
          "bounds": [1e-5, 2e-1],
          "value_type": "float",
          "log_scale": True
        },
        {
          "name": "betas0",
          "type": "range",
          "bounds": [1e-5, 2e-1],
          "value_type": "float",
          "log_scale": True
        },
        {
          "name": "betas1",
          "type": "range",
          "bounds": [1e-5, 2e-1],
          "value_type": "float",
          "log_scale": True
        }
    ],
    parameter_constraints=["0.02 * n_epochs + -1 * batch_size <= 0"],
    evaluation_function=train_evaluate,
    minimize=False,
    arms_per_trial=5,
    total_trials=1,
    outcome_constraints=None,
    experiment_name="Test"
)

with open("hyperparameters.pl", "wb") as handle:
    pickle.dump(optim_result, handle, protocol = pickle.HIGHEST_PROTOCOL)


[INFO 08-29 04:44:33] ax.service.utils.dispatch: Using Bayesian Optimization generation strategy: GenerationStrategy(name='Sobol+GPEI', steps=[Sobol for 10 arms, GPEI for subsequent arms], generated 0 arm(s) so far). Iterations after 10 will take longer to generate due to model-fitting.
[INFO 08-29 04:44:33] ax.service.managed_loop: Started full optimization with 20 steps.
[INFO 08-29 04:44:33] ax.service.managed_loop: Running optimization trial 1...
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([4021])) that is different to the input size (torch.Size([4021, 1])) is deprecated. Please ensure they have the same size.



Testing out: 
batch_size:  4242
train_size:  4021
n_epochs:  151
lr:  0.2059096003537947
weight_decay:  1.3539379101203248e-05
betas0:  0.9991187551142399
betas1:  0.99
hidden_size:  10
conv1.weight tensor([[[[-0.2991, -0.1502, -0.0728],
          [ 0.2323,  0.1664,  0.2349],
          [ 0.1562,  0.0104,  0.2755]]]])
conv1.bias tensor([-0.2626])
first_linear.weight tensor([[-0.0826, -0.2689, -0.3244,  0.1389,  0.1754,  0.2683, -0.3155,  0.3206,
          0.1242],
        [ 0.0380,  0.2689,  0.3005, -0.0990,  0.0419, -0.1171, -0.1438,  0.1863,
          0.2644],
        [ 0.1571,  0.0092, -0.2080,  0.0356, -0.0879,  0.0993, -0.2621,  0.2306,
          0.0268],
        [-0.0141,  0.2197,  0.1910,  0.0198, -0.1197, -0.2907, -0.1822,  0.0351,
         -0.2345],
        [-0.1890,  0.0083,  0.3227, -0.2668, -0.1922,  0.2219,  0.2488,  0.2886,
          0.2395],
        [-0.0546, -0.1337,  0.3327, -0.0301, -0.1337,  0.2902,  0.3136,  0.1033,
         -0.0965],
        [ 0.3192,  0.3298, -0.25

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([268])) that is different to the input size (torch.Size([268, 1])) is deprecated. Please ensure they have the same size.



Epoch: 9 	 Train Loss: 0.7046806812286377 	 Validate_Accuracy: 0.503
epoch 10
Epoch: 10 	 Train Loss: 0.7043759822845459 	 Validate_Accuracy: 0.5035
epoch 11
Epoch: 11 	 Train Loss: 0.7040738463401794 	 Validate_Accuracy: 0.5035
epoch 12
Epoch: 12 	 Train Loss: 0.7037736773490906 	 Validate_Accuracy: 0.5035
epoch 13
Epoch: 13 	 Train Loss: 0.703475832939148 	 Validate_Accuracy: 0.5035
epoch 14
Epoch: 14 	 Train Loss: 0.7031807899475098 	 Validate_Accuracy: 0.503
epoch 15
Epoch: 15 	 Train Loss: 0.7028876543045044 	 Validate_Accuracy: 0.504
epoch 16
Epoch: 16 	 Train Loss: 0.7025976181030273 	 Validate_Accuracy: 0.5035
epoch 17
Epoch: 17 	 Train Loss: 0.7023091316223145 	 Validate_Accuracy: 0.5035
epoch 18
Epoch: 18 	 Train Loss: 0.7020238041877747 	 Validate_Accuracy: 0.503
epoch 19
Epoch: 19 	 Train Loss: 0.7017409205436707 	 Validate_Accuracy: 0.504
epoch 20
Epoch: 20 	 Train Loss: 0.7014603018760681 	 Validate_Accuracy: 0.505
epoch 21
Epoch: 21 	 Train Loss: 0.7011823654174805 	 Val

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([2090])) that is different to the input size (torch.Size([2090, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([1132])) that is different to the input size (torch.Size([1132, 1])) is deprecated. Please ensure they have the same size.



Epoch: 2 	 Train Loss: 0.6881621181964874 	 Validate_Accuracy: 0.536
epoch 3
Epoch: 3 	 Train Loss: 0.6879068613052368 	 Validate_Accuracy: 0.502
epoch 4
Epoch: 4 	 Train Loss: 0.683305025100708 	 Validate_Accuracy: 0.6045
epoch 5
Epoch: 5 	 Train Loss: 0.6724039614200592 	 Validate_Accuracy: 0.601
epoch 6
Epoch: 6 	 Train Loss: 0.6546335816383362 	 Validate_Accuracy: 0.7025
epoch 7
Epoch: 7 	 Train Loss: 0.6202370524406433 	 Validate_Accuracy: 0.779
epoch 8
Epoch: 8 	 Train Loss: 0.577989012002945 	 Validate_Accuracy: 0.794
epoch 9
Epoch: 9 	 Train Loss: 0.5234812498092651 	 Validate_Accuracy: 0.829
epoch 10
Epoch: 10 	 Train Loss: 0.47700898349285126 	 Validate_Accuracy: 0.8175
epoch 11
Epoch: 11 	 Train Loss: 0.44731713831424713 	 Validate_Accuracy: 0.8045
epoch 12
Epoch: 12 	 Train Loss: 0.4374745637178421 	 Validate_Accuracy: 0.8195
epoch 13
Epoch: 13 	 Train Loss: 0.4431181848049164 	 Validate_Accuracy: 0.812
epoch 14
Epoch: 14 	 Train Loss: 0.4103652983903885 	 Validate_Accuracy

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([848])) that is different to the input size (torch.Size([848, 1])) is deprecated. Please ensure they have the same size.



Epoch: 1 	 Train Loss: 0.7016726732254028 	 Validate_Accuracy: 0.497
epoch 2
Epoch: 2 	 Train Loss: 0.7004754543304443 	 Validate_Accuracy: 0.497
epoch 3
Epoch: 3 	 Train Loss: 0.6993572115898132 	 Validate_Accuracy: 0.497
epoch 4
Epoch: 4 	 Train Loss: 0.6983165144920349 	 Validate_Accuracy: 0.497
epoch 5
Epoch: 5 	 Train Loss: 0.6973515152931213 	 Validate_Accuracy: 0.497
epoch 6
Epoch: 6 	 Train Loss: 0.696456789970398 	 Validate_Accuracy: 0.497
epoch 7
Epoch: 7 	 Train Loss: 0.6956295967102051 	 Validate_Accuracy: 0.497
epoch 8
Epoch: 8 	 Train Loss: 0.6948613524436951 	 Validate_Accuracy: 0.497
epoch 9
Epoch: 9 	 Train Loss: 0.6941515803337097 	 Validate_Accuracy: 0.497
epoch 10
Epoch: 10 	 Train Loss: 0.6934939622879028 	 Validate_Accuracy: 0.497
epoch 11
Epoch: 11 	 Train Loss: 0.6928831934928894 	 Validate_Accuracy: 0.497
epoch 12
Epoch: 12 	 Train Loss: 0.6923156380653381 	 Validate_Accuracy: 0.497
epoch 13
Epoch: 13 	 Train Loss: 0.6917862892150879 	 Validate_Accuracy: 0.497


/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([2562])) that is different to the input size (torch.Size([2562, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([235])) that is different to the input size (torch.Size([235, 1])) is deprecated. Please ensure they have the same size.



Epoch: 1 	 Train Loss: 0.761236846446991 	 Validate_Accuracy: 0.4745
epoch 2
Epoch: 2 	 Train Loss: 1.0149559676647186 	 Validate_Accuracy: 0.593
epoch 3
Epoch: 3 	 Train Loss: 0.7085904777050018 	 Validate_Accuracy: 0.417
epoch 4
Epoch: 4 	 Train Loss: 0.7387906610965729 	 Validate_Accuracy: 0.6165
epoch 5
Epoch: 5 	 Train Loss: 0.6341555714607239 	 Validate_Accuracy: 0.663
epoch 6
Epoch: 6 	 Train Loss: 0.6019546985626221 	 Validate_Accuracy: 0.725
epoch 7
Epoch: 7 	 Train Loss: 0.5720411837100983 	 Validate_Accuracy: 0.655
epoch 8
Epoch: 8 	 Train Loss: 0.5556181371212006 	 Validate_Accuracy: 0.7725
epoch 9
Epoch: 9 	 Train Loss: 0.5435733795166016 	 Validate_Accuracy: 0.794
epoch 10
Epoch: 10 	 Train Loss: 0.49341633915901184 	 Validate_Accuracy: 0.7805
epoch 11
Epoch: 11 	 Train Loss: 0.49670206010341644 	 Validate_Accuracy: 0.811
epoch 12
Epoch: 12 	 Train Loss: 0.4873667359352112 	 Validate_Accuracy: 0.807
epoch 13
Epoch: 13 	 Train Loss: 0.530965581536293 	 Validate_Accuracy: 0

[INFO 08-29 04:45:38] ax.service.managed_loop: Running optimization trial 2...


Epoch: 111 	 Train Loss: 0.4230744242668152 	 Validate_Accuracy: 0.818
epoch 112
Epoch: 112 	 Train Loss: 0.427002415060997 	 Validate_Accuracy: 0.8215
model parameters! 

conv1.weight tensor([[[[ 0.4353,  0.2995,  0.1776],
          [ 0.4093, -0.0217,  0.4423],
          [ 0.3078,  0.1560,  0.4550]]]])
conv1.bias tensor([0.0535])
first_linear.weight tensor([[-0.2283,  0.0580, -0.0557, -0.1622,  0.0533, -0.0237, -0.2513, -0.0357,
          0.1293],
        [-0.0684, -0.1042,  0.0265, -0.0051, -0.1942, -0.1104, -0.0928, -0.1016,
         -0.3626],
        [ 0.1035,  0.0494, -0.0499, -0.1441,  0.0489,  0.0742,  0.0325,  0.1293,
          0.3516],
        [-0.0297, -0.1061, -0.3063,  0.1392, -0.2816, -0.5844,  0.1403,  0.0107,
         -0.3679],
        [ 0.1194,  0.2122, -0.0599,  0.0033,  0.1717,  0.1041, -0.0054, -0.0755,
          0.2286],
        [-0.3472, -0.1230,  0.1820, -0.6748, -0.3763, -0.0243, -0.4404, -0.1573,
         -0.1046],
        [ 0.2990,  0.3735,  0.1273,  0.3150,  0

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([1496])) that is different to the input size (torch.Size([1496, 1])) is deprecated. Please ensure they have the same size.



Epoch: 1 	 Train Loss: 0.6964678168296814 	 Validate_Accuracy: 0.48
epoch 2
Epoch: 2 	 Train Loss: 0.696405827999115 	 Validate_Accuracy: 0.4805
epoch 3
Epoch: 3 	 Train Loss: 0.6963456869125366 	 Validate_Accuracy: 0.4795
epoch 4
Epoch: 4 	 Train Loss: 0.6962863802909851 	 Validate_Accuracy: 0.479
epoch 5
Epoch: 5 	 Train Loss: 0.6962275505065918 	 Validate_Accuracy: 0.4795
epoch 6
Epoch: 6 	 Train Loss: 0.6961707472801208 	 Validate_Accuracy: 0.479
epoch 7
Epoch: 7 	 Train Loss: 0.6961139440536499 	 Validate_Accuracy: 0.479
epoch 8
Epoch: 8 	 Train Loss: 0.6960570216178894 	 Validate_Accuracy: 0.4775
epoch 9
Epoch: 9 	 Train Loss: 0.6960023045539856 	 Validate_Accuracy: 0.4785
epoch 10
Epoch: 10 	 Train Loss: 0.6959474682807922 	 Validate_Accuracy: 0.478
epoch 11
Epoch: 11 	 Train Loss: 0.6958920955657959 	 Validate_Accuracy: 0.4785
epoch 12
Epoch: 12 	 Train Loss: 0.695838987827301 	 Validate_Accuracy: 0.479
epoch 13
Epoch: 13 	 Train Loss: 0.6957864165306091 	 Validate_Accuracy: 0.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([956])) that is different to the input size (torch.Size([956, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([623])) that is different to the input size (torch.Size([623, 1])) is deprecated. Please ensure they have the same size.



Epoch: 2 	 Train Loss: 0.6930514335632324 	 Validate_Accuracy: 0.524
epoch 3
Epoch: 3 	 Train Loss: 0.681201946735382 	 Validate_Accuracy: 0.708
epoch 4
Epoch: 4 	 Train Loss: 0.6379942774772644 	 Validate_Accuracy: 0.803
epoch 5
Epoch: 5 	 Train Loss: 0.5618987798690795 	 Validate_Accuracy: 0.797
epoch 6
Epoch: 6 	 Train Loss: 0.4829409122467041 	 Validate_Accuracy: 0.7955
epoch 7
Epoch: 7 	 Train Loss: 0.45164580941200255 	 Validate_Accuracy: 0.8045
epoch 8
Epoch: 8 	 Train Loss: 0.4204069197177887 	 Validate_Accuracy: 0.807
epoch 9
Epoch: 9 	 Train Loss: 0.39954766631126404 	 Validate_Accuracy: 0.819
epoch 10
Epoch: 10 	 Train Loss: 0.37166479229927063 	 Validate_Accuracy: 0.831
epoch 11
Epoch: 11 	 Train Loss: 0.3484026253223419 	 Validate_Accuracy: 0.8365
epoch 12
Epoch: 12 	 Train Loss: 0.3400856971740723 	 Validate_Accuracy: 0.833
epoch 13
Epoch: 13 	 Train Loss: 0.3273621737957001 	 Validate_Accuracy: 0.8515
epoch 14
Epoch: 14 	 Train Loss: 0.32858832478523253 	 Validate_Accura

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([669])) that is different to the input size (torch.Size([669, 1])) is deprecated. Please ensure they have the same size.



Epoch: 1 	 Train Loss: 0.6882159113883972 	 Validate_Accuracy: 0.497
epoch 2
Epoch: 2 	 Train Loss: 1.8460215330123901 	 Validate_Accuracy: 0.5605
epoch 3
Epoch: 3 	 Train Loss: 2.4899582862854004 	 Validate_Accuracy: 0.5305
epoch 4
Epoch: 4 	 Train Loss: 1.3706258535385132 	 Validate_Accuracy: 0.48
epoch 5
Epoch: 5 	 Train Loss: 1.3583641052246094 	 Validate_Accuracy: 0.5795
epoch 6
Epoch: 6 	 Train Loss: 1.0117826461791992 	 Validate_Accuracy: 0.505
epoch 7
Epoch: 7 	 Train Loss: 1.0609171390533447 	 Validate_Accuracy: 0.5195
epoch 8
Epoch: 8 	 Train Loss: 0.869448721408844 	 Validate_Accuracy: 0.606
epoch 9
Epoch: 9 	 Train Loss: 0.8168125152587891 	 Validate_Accuracy: 0.525
epoch 10
Epoch: 10 	 Train Loss: 0.8284881114959717 	 Validate_Accuracy: 0.6305
epoch 11
Epoch: 11 	 Train Loss: 0.7296432256698608 	 Validate_Accuracy: 0.625
epoch 12
Epoch: 12 	 Train Loss: 0.7133619785308838 	 Validate_Accuracy: 0.6205
epoch 13
Epoch: 13 	 Train Loss: 0.7326235175132751 	 Validate_Accuracy: 0

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([3591])) that is different to the input size (torch.Size([3591, 1])) is deprecated. Please ensure they have the same size.



Epoch: 2 	 Train Loss: 0.6940745711326599 	 Validate_Accuracy: 0.493
epoch 3
Epoch: 3 	 Train Loss: 0.6940128207206726 	 Validate_Accuracy: 0.499
epoch 4
Epoch: 4 	 Train Loss: 0.6939554810523987 	 Validate_Accuracy: 0.5065
epoch 5
Epoch: 5 	 Train Loss: 0.6939035654067993 	 Validate_Accuracy: 0.508
epoch 6
Epoch: 6 	 Train Loss: 0.6938562393188477 	 Validate_Accuracy: 0.511
epoch 7
Epoch: 7 	 Train Loss: 0.693810224533081 	 Validate_Accuracy: 0.517
epoch 8
Epoch: 8 	 Train Loss: 0.6937682032585144 	 Validate_Accuracy: 0.5165
epoch 9
Epoch: 9 	 Train Loss: 0.6937322616577148 	 Validate_Accuracy: 0.521
epoch 10
Epoch: 10 	 Train Loss: 0.6936966180801392 	 Validate_Accuracy: 0.523
epoch 11
Epoch: 11 	 Train Loss: 0.6936655640602112 	 Validate_Accuracy: 0.5245
epoch 12
Epoch: 12 	 Train Loss: 0.6936352849006653 	 Validate_Accuracy: 0.5285
epoch 13
Epoch: 13 	 Train Loss: 0.6936059594154358 	 Validate_Accuracy: 0.5295
epoch 14
Epoch: 14 	 Train Loss: 0.6935812830924988 	 Validate_Accuracy:

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([2288])) that is different to the input size (torch.Size([2288, 1])) is deprecated. Please ensure they have the same size.



Epoch: 3 	 Train Loss: 0.6925312280654907 	 Validate_Accuracy: 0.512
epoch 4
Epoch: 4 	 Train Loss: 0.6923137903213501 	 Validate_Accuracy: 0.519
epoch 5
Epoch: 5 	 Train Loss: 0.6920631527900696 	 Validate_Accuracy: 0.509
epoch 6
Epoch: 6 	 Train Loss: 0.6917945742607117 	 Validate_Accuracy: 0.4755
epoch 7
Epoch: 7 	 Train Loss: 0.6914491057395935 	 Validate_Accuracy: 0.463
epoch 8
Epoch: 8 	 Train Loss: 0.690963625907898 	 Validate_Accuracy: 0.467
epoch 9
Epoch: 9 	 Train Loss: 0.690316915512085 	 Validate_Accuracy: 0.5005
epoch 10
Epoch: 10 	 Train Loss: 0.6895083785057068 	 Validate_Accuracy: 0.5275
epoch 11
Epoch: 11 	 Train Loss: 0.6885343194007874 	 Validate_Accuracy: 0.5305
epoch 12
Epoch: 12 	 Train Loss: 0.6873735189437866 	 Validate_Accuracy: 0.529
epoch 13
Epoch: 13 	 Train Loss: 0.6859807968139648 	 Validate_Accuracy: 0.5325
epoch 14
Epoch: 14 	 Train Loss: 0.6843144297599792 	 Validate_Accuracy: 0.5415
epoch 15
Epoch: 15 	 Train Loss: 0.6823562979698181 	 Validate_Accurac

[INFO 08-29 04:47:16] ax.service.managed_loop: Running optimization trial 3...


Epoch: 169 	 Train Loss: 0.2298341542482376 	 Validate_Accuracy: 0.8795
epoch 170
Epoch: 170 	 Train Loss: 0.2296798825263977 	 Validate_Accuracy: 0.881
model parameters! 

conv1.weight tensor([[[[ 0.1890,  0.0956,  0.2264],
          [ 0.1039, -0.0134,  0.0944],
          [ 0.1851,  0.0921,  0.2125]]]])
conv1.bias tensor([-0.0414])
first_linear.weight tensor([[-0.3583,  0.1417,  0.2936,  0.9192, -0.7272, -0.1892, -0.7389,  1.0965,
         -0.2528],
        [-0.7322,  0.5618, -0.0779, -0.0534,  0.1706, -0.3218,  0.5711, -0.7204,
          0.3582],
        [-0.0121,  0.0459,  0.0506,  0.1026,  0.0691,  0.1288, -0.0073, -0.0836,
          0.0907],
        [-0.1399, -0.0709,  0.1203, -0.3317, -0.3297, -0.3038, -0.2158, -0.2080,
         -0.2104],
        [ 0.0597, -0.2875,  0.0448, -0.2814, -0.0887,  0.0862, -0.4288, -0.5867,
          0.0502],
        [ 0.2537,  0.3526,  0.2002,  0.1719,  0.1959,  0.0047,  0.0601,  0.1691,
         -0.1834],
        [ 0.3898,  0.3368, -0.4466, -0.7184, 

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([2222])) that is different to the input size (torch.Size([2222, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([773])) that is different to the input size (torch.Size([773, 1])) is deprecated. Please ensure they have the same size.



Epoch: 2 	 Train Loss: 0.6924384534358978 	 Validate_Accuracy: 0.5015
epoch 3
Epoch: 3 	 Train Loss: 0.6871255934238434 	 Validate_Accuracy: 0.59
epoch 4
Epoch: 4 	 Train Loss: 0.6752354502677917 	 Validate_Accuracy: 0.667
epoch 5
Epoch: 5 	 Train Loss: 0.6584599614143372 	 Validate_Accuracy: 0.6585
epoch 6
Epoch: 6 	 Train Loss: 0.6295489072799683 	 Validate_Accuracy: 0.7225
epoch 7
Epoch: 7 	 Train Loss: 0.5873101055622101 	 Validate_Accuracy: 0.7565
epoch 8
Epoch: 8 	 Train Loss: 0.5465005040168762 	 Validate_Accuracy: 0.783
epoch 9
Epoch: 9 	 Train Loss: 0.5024086236953735 	 Validate_Accuracy: 0.79
epoch 10
Epoch: 10 	 Train Loss: 0.4566221535205841 	 Validate_Accuracy: 0.801
epoch 11
Epoch: 11 	 Train Loss: 0.4166407436132431 	 Validate_Accuracy: 0.821
epoch 12
Epoch: 12 	 Train Loss: 0.38885578513145447 	 Validate_Accuracy: 0.8335
epoch 13
Epoch: 13 	 Train Loss: 0.3721844255924225 	 Validate_Accuracy: 0.8335
epoch 14
Epoch: 14 	 Train Loss: 0.34987665712833405 	 Validate_Accurac

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([2264])) that is different to the input size (torch.Size([2264, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([927])) that is different to the input size (torch.Size([927, 1])) is deprecated. Please ensure they have the same size.



Epoch: 2 	 Train Loss: 0.6913417279720306 	 Validate_Accuracy: 0.512
epoch 3
Epoch: 3 	 Train Loss: 0.6903115510940552 	 Validate_Accuracy: 0.5235
epoch 4
Epoch: 4 	 Train Loss: 0.6870336532592773 	 Validate_Accuracy: 0.574
epoch 5
Epoch: 5 	 Train Loss: 0.6829624474048615 	 Validate_Accuracy: 0.599
epoch 6
Epoch: 6 	 Train Loss: 0.6751400232315063 	 Validate_Accuracy: 0.598
epoch 7
Epoch: 7 	 Train Loss: 0.663835197687149 	 Validate_Accuracy: 0.6605
epoch 8
Epoch: 8 	 Train Loss: 0.640969306230545 	 Validate_Accuracy: 0.7025
epoch 9
Epoch: 9 	 Train Loss: 0.6174843907356262 	 Validate_Accuracy: 0.7275
epoch 10
Epoch: 10 	 Train Loss: 0.5831946730613708 	 Validate_Accuracy: 0.7735
epoch 11
Epoch: 11 	 Train Loss: 0.5370382964611053 	 Validate_Accuracy: 0.8205
epoch 12
Epoch: 12 	 Train Loss: 0.4897811710834503 	 Validate_Accuracy: 0.8385
epoch 13
Epoch: 13 	 Train Loss: 0.4442640244960785 	 Validate_Accuracy: 0.8455
epoch 14
Epoch: 14 	 Train Loss: 0.39919690787792206 	 Validate_Accura

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([1897])) that is different to the input size (torch.Size([1897, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([38])) that is different to the input size (torch.Size([38, 1])) is deprecated. Please ensure they have the same size.



Epoch: 3 	 Train Loss: 0.6982326209545135 	 Validate_Accuracy: 0.523
epoch 4
Epoch: 4 	 Train Loss: 0.6907370090484619 	 Validate_Accuracy: 0.503
epoch 5
Epoch: 5 	 Train Loss: 0.70530766248703 	 Validate_Accuracy: 0.503
epoch 6
Epoch: 6 	 Train Loss: 0.6925854086875916 	 Validate_Accuracy: 0.503
epoch 7
Epoch: 7 	 Train Loss: 0.6915650367736816 	 Validate_Accuracy: 0.5015
epoch 8
Epoch: 8 	 Train Loss: 0.6912851333618164 	 Validate_Accuracy: 0.4995
epoch 9
Epoch: 9 	 Train Loss: 0.6893599927425385 	 Validate_Accuracy: 0.502
epoch 10
Epoch: 10 	 Train Loss: 0.6977558732032776 	 Validate_Accuracy: 0.5025
epoch 11
Epoch: 11 	 Train Loss: 0.7003382444381714 	 Validate_Accuracy: 0.488
epoch 12
Epoch: 12 	 Train Loss: 0.6911355555057526 	 Validate_Accuracy: 0.4835
epoch 13
Epoch: 13 	 Train Loss: 0.6932529509067535 	 Validate_Accuracy: 0.5715
epoch 14
Epoch: 14 	 Train Loss: 0.6981471478939056 	 Validate_Accuracy: 0.5695
epoch 15
Epoch: 15 	 Train Loss: 0.6928704082965851 	 Validate_Accurac

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([3008])) that is different to the input size (torch.Size([3008, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([282])) that is different to the input size (torch.Size([282, 1])) is deprecated. Please ensure they have the same size.



Epoch: 1 	 Train Loss: 0.722647488117218 	 Validate_Accuracy: 0.457
epoch 2
Epoch: 2 	 Train Loss: 0.7020787596702576 	 Validate_Accuracy: 0.5595
epoch 3
Epoch: 3 	 Train Loss: 0.6838515400886536 	 Validate_Accuracy: 0.7385
epoch 4
Epoch: 4 	 Train Loss: 0.6439616084098816 	 Validate_Accuracy: 0.6305
epoch 5
Epoch: 5 	 Train Loss: 0.5943869650363922 	 Validate_Accuracy: 0.7855
epoch 6
Epoch: 6 	 Train Loss: 0.5597705841064453 	 Validate_Accuracy: 0.7885
epoch 7
Epoch: 7 	 Train Loss: 0.49048852920532227 	 Validate_Accuracy: 0.7925
epoch 8
Epoch: 8 	 Train Loss: 0.4641948491334915 	 Validate_Accuracy: 0.8085
epoch 9
Epoch: 9 	 Train Loss: 0.4625054597854614 	 Validate_Accuracy: 0.8095
epoch 10
Epoch: 10 	 Train Loss: 0.4640205502510071 	 Validate_Accuracy: 0.806
epoch 11
Epoch: 11 	 Train Loss: 0.42287661135196686 	 Validate_Accuracy: 0.817
epoch 12
Epoch: 12 	 Train Loss: 0.3925122916698456 	 Validate_Accuracy: 0.82
epoch 13
Epoch: 13 	 Train Loss: 0.4104124754667282 	 Validate_Accurac

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([1872])) that is different to the input size (torch.Size([1872, 1])) is deprecated. Please ensure they have the same size.



Epoch: 3 	 Train Loss: 0.6931778192520142 	 Validate_Accuracy: 0.503
epoch 4
Epoch: 4 	 Train Loss: 0.6935097575187683 	 Validate_Accuracy: 0.503
epoch 5
Epoch: 5 	 Train Loss: 0.693374514579773 	 Validate_Accuracy: 0.503
epoch 6
Epoch: 6 	 Train Loss: 0.6931518912315369 	 Validate_Accuracy: 0.497
epoch 7
Epoch: 7 	 Train Loss: 0.6931872963905334 	 Validate_Accuracy: 0.497
epoch 8
Epoch: 8 	 Train Loss: 0.693253219127655 	 Validate_Accuracy: 0.497
epoch 9
Epoch: 9 	 Train Loss: 0.6932234168052673 	 Validate_Accuracy: 0.528
epoch 10
Epoch: 10 	 Train Loss: 0.6931880712509155 	 Validate_Accuracy: 0.503
epoch 11
Epoch: 11 	 Train Loss: 0.6931976675987244 	 Validate_Accuracy: 0.503
epoch 12
Epoch: 12 	 Train Loss: 0.6931992173194885 	 Validate_Accuracy: 0.503
epoch 13
Epoch: 13 	 Train Loss: 0.6931681632995605 	 Validate_Accuracy: 0.503
epoch 14
Epoch: 14 	 Train Loss: 0.6931375861167908 	 Validate_Accuracy: 0.5055
epoch 15
Epoch: 15 	 Train Loss: 0.6931324005126953 	 Validate_Accuracy: 0.

[INFO 08-29 04:48:38] ax.service.managed_loop: Running optimization trial 4...


Epoch: 131 	 Train Loss: 0.6931514143943787 	 Validate_Accuracy: 0.497
epoch 132
Epoch: 132 	 Train Loss: 0.6931402683258057 	 Validate_Accuracy: 0.497
model parameters! 

conv1.weight tensor([[[[ 1.0225e-04, -2.3852e-04,  1.1042e-04],
          [-1.1696e-05, -1.6007e-04, -7.0560e-05],
          [ 3.0371e-05,  6.5589e-05, -1.0628e-04]]]])
conv1.bias tensor([1.0584e-05])
first_linear.weight tensor([[ 5.7359e-05, -7.3786e-05, -4.7194e-05, -1.8388e-04,  1.5524e-04,
         -1.7461e-04,  2.6416e-04,  9.2422e-05,  2.2417e-05],
        [-2.1082e-04,  1.2942e-04, -1.7003e-05,  3.0321e-04, -1.3096e-04,
         -8.9947e-05,  2.5285e-05,  7.8906e-05, -1.6496e-04],
        [ 9.1873e-05, -1.2702e-04,  8.5634e-05,  7.2277e-05, -1.8014e-04,
         -1.4082e-04,  4.9030e-05,  1.8410e-04, -1.6441e-04],
        [-2.0205e-04, -8.5576e-05, -1.7687e-04, -2.2022e-05, -5.6651e-05,
          5.6666e-05, -9.8068e-05,  2.4152e-05, -7.0768e-05],
        [-5.8225e-05, -8.5229e-05,  1.2526e-04,  1.6176e-05, -5

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([2332])) that is different to the input size (torch.Size([2332, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([812])) that is different to the input size (torch.Size([812, 1])) is deprecated. Please ensure they have the same size.



Epoch: 2 	 Train Loss: 0.692741721868515 	 Validate_Accuracy: 0.498
epoch 3
Epoch: 3 	 Train Loss: 0.6922445297241211 	 Validate_Accuracy: 0.4995
epoch 4
Epoch: 4 	 Train Loss: 0.6925562620162964 	 Validate_Accuracy: 0.4985
epoch 5
Epoch: 5 	 Train Loss: 0.6914000809192657 	 Validate_Accuracy: 0.5095
epoch 6
Epoch: 6 	 Train Loss: 0.6922825574874878 	 Validate_Accuracy: 0.5235
epoch 7
Epoch: 7 	 Train Loss: 0.6907959580421448 	 Validate_Accuracy: 0.5555
epoch 8
Epoch: 8 	 Train Loss: 0.689902275800705 	 Validate_Accuracy: 0.54
epoch 9
Epoch: 9 	 Train Loss: 0.6898767352104187 	 Validate_Accuracy: 0.52
epoch 10
Epoch: 10 	 Train Loss: 0.6886282563209534 	 Validate_Accuracy: 0.5475
epoch 11
Epoch: 11 	 Train Loss: 0.6856730282306671 	 Validate_Accuracy: 0.5695
epoch 12
Epoch: 12 	 Train Loss: 0.6834085285663605 	 Validate_Accuracy: 0.58
epoch 13
Epoch: 13 	 Train Loss: 0.6770150363445282 	 Validate_Accuracy: 0.5905
epoch 14
Epoch: 14 	 Train Loss: 0.6742397844791412 	 Validate_Accuracy: 

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([2205])) that is different to the input size (torch.Size([2205, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([1806])) that is different to the input size (torch.Size([1806, 1])) is deprecated. Please ensure they have the same size.



Epoch: 2 	 Train Loss: 0.7013376355171204 	 Validate_Accuracy: 0.5215
epoch 3
Epoch: 3 	 Train Loss: 0.6939294934272766 	 Validate_Accuracy: 0.602
epoch 4
Epoch: 4 	 Train Loss: 0.6930208802223206 	 Validate_Accuracy: 0.64
epoch 5
Epoch: 5 	 Train Loss: 0.6695746183395386 	 Validate_Accuracy: 0.623
epoch 6
Epoch: 6 	 Train Loss: 0.6305927336215973 	 Validate_Accuracy: 0.8
epoch 7
Epoch: 7 	 Train Loss: 0.581356942653656 	 Validate_Accuracy: 0.794
epoch 8
Epoch: 8 	 Train Loss: 0.5588324964046478 	 Validate_Accuracy: 0.8145
epoch 9
Epoch: 9 	 Train Loss: 0.5361921191215515 	 Validate_Accuracy: 0.7965
epoch 10
Epoch: 10 	 Train Loss: 0.5139469057321548 	 Validate_Accuracy: 0.7995
epoch 11
Epoch: 11 	 Train Loss: 0.4890759587287903 	 Validate_Accuracy: 0.817
epoch 12
Epoch: 12 	 Train Loss: 0.46256645023822784 	 Validate_Accuracy: 0.817
epoch 13
Epoch: 13 	 Train Loss: 0.4482661187648773 	 Validate_Accuracy: 0.821
epoch 14
Epoch: 14 	 Train Loss: 0.43730056285858154 	 Validate_Accuracy: 0

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([2034])) that is different to the input size (torch.Size([2034, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([1686])) that is different to the input size (torch.Size([1686, 1])) is deprecated. Please ensure they have the same size.



Epoch: 1 	 Train Loss: 0.6939334273338318 	 Validate_Accuracy: 0.5045
epoch 2
Epoch: 2 	 Train Loss: 0.6930422186851501 	 Validate_Accuracy: 0.549
epoch 3
Epoch: 3 	 Train Loss: 0.6895143389701843 	 Validate_Accuracy: 0.5635
epoch 4
Epoch: 4 	 Train Loss: 0.6822512745857239 	 Validate_Accuracy: 0.613
epoch 5
Epoch: 5 	 Train Loss: 0.6720125675201416 	 Validate_Accuracy: 0.696
epoch 6
Epoch: 6 	 Train Loss: 0.6563305258750916 	 Validate_Accuracy: 0.731
epoch 7
Epoch: 7 	 Train Loss: 0.6294540166854858 	 Validate_Accuracy: 0.7805
epoch 8
Epoch: 8 	 Train Loss: 0.5963761806488037 	 Validate_Accuracy: 0.7945
epoch 9
Epoch: 9 	 Train Loss: 0.5550357699394226 	 Validate_Accuracy: 0.8045
epoch 10
Epoch: 10 	 Train Loss: 0.514647051692009 	 Validate_Accuracy: 0.8155
epoch 11
Epoch: 11 	 Train Loss: 0.4805714040994644 	 Validate_Accuracy: 0.8085
epoch 12
Epoch: 12 	 Train Loss: 0.46248410642147064 	 Validate_Accuracy: 0.816
epoch 13
Epoch: 13 	 Train Loss: 0.456659734249115 	 Validate_Accuracy:

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([1585])) that is different to the input size (torch.Size([1585, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([1471])) that is different to the input size (torch.Size([1471, 1])) is deprecated. Please ensure they have the same size.



Epoch: 1 	 Train Loss: 0.699898362159729 	 Validate_Accuracy: 0.4975
epoch 2
Epoch: 2 	 Train Loss: 0.6939094066619873 	 Validate_Accuracy: 0.4965
epoch 3
Epoch: 3 	 Train Loss: 0.6938530504703522 	 Validate_Accuracy: 0.503
epoch 4
Epoch: 4 	 Train Loss: 0.6941068172454834 	 Validate_Accuracy: 0.5025
epoch 5
Epoch: 5 	 Train Loss: 0.6932136416435242 	 Validate_Accuracy: 0.4935
epoch 6
Epoch: 6 	 Train Loss: 0.6923547387123108 	 Validate_Accuracy: 0.51
epoch 7
Epoch: 7 	 Train Loss: 0.692139059305191 	 Validate_Accuracy: 0.533
epoch 8
Epoch: 8 	 Train Loss: 0.6922759711742401 	 Validate_Accuracy: 0.5265
epoch 9
Epoch: 9 	 Train Loss: 0.6921650469303131 	 Validate_Accuracy: 0.528
epoch 10
Epoch: 10 	 Train Loss: 0.6918770372867584 	 Validate_Accuracy: 0.523
epoch 11
Epoch: 11 	 Train Loss: 0.6914798021316528 	 Validate_Accuracy: 0.5025
epoch 12
Epoch: 12 	 Train Loss: 0.6911638081073761 	 Validate_Accuracy: 0.486
epoch 13
Epoch: 13 	 Train Loss: 0.6908861398696899 	 Validate_Accuracy: 0.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([2757])) that is different to the input size (torch.Size([2757, 1])) is deprecated. Please ensure they have the same size.



Epoch: 1 	 Train Loss: 0.6953843832015991 	 Validate_Accuracy: 0.562
epoch 2
Epoch: 2 	 Train Loss: 0.6926686763763428 	 Validate_Accuracy: 0.596
epoch 3
Epoch: 3 	 Train Loss: 0.6918340921401978 	 Validate_Accuracy: 0.596
epoch 4
Epoch: 4 	 Train Loss: 0.6880099177360535 	 Validate_Accuracy: 0.582
epoch 5
Epoch: 5 	 Train Loss: 0.6829966902732849 	 Validate_Accuracy: 0.577
epoch 6
Epoch: 6 	 Train Loss: 0.6768367290496826 	 Validate_Accuracy: 0.592
epoch 7
Epoch: 7 	 Train Loss: 0.6692969799041748 	 Validate_Accuracy: 0.7075
epoch 8
Epoch: 8 	 Train Loss: 0.6598590016365051 	 Validate_Accuracy: 0.76
epoch 9
Epoch: 9 	 Train Loss: 0.6478948593139648 	 Validate_Accuracy: 0.7835
epoch 10
Epoch: 10 	 Train Loss: 0.6330809593200684 	 Validate_Accuracy: 0.7915
epoch 11
Epoch: 11 	 Train Loss: 0.6157342791557312 	 Validate_Accuracy: 0.7915
epoch 12
Epoch: 12 	 Train Loss: 0.5968484878540039 	 Validate_Accuracy: 0.7995
epoch 13
Epoch: 13 	 Train Loss: 0.5777756571769714 	 Validate_Accuracy: 0

[INFO 08-29 04:50:40] ax.service.managed_loop: Running optimization trial 5...


Epoch: 178 	 Train Loss: 0.2072668969631195 	 Validate_Accuracy: 0.889
epoch 179
Epoch: 179 	 Train Loss: 0.20617122948169708 	 Validate_Accuracy: 0.888
model parameters! 

conv1.weight tensor([[[[-0.1106, -0.0478, -0.1339],
          [-0.0570,  0.0096, -0.0358],
          [-0.1052, -0.0399, -0.1315]]]])
conv1.bias tensor([0.1053])
first_linear.weight tensor([[ 3.0744e-01,  6.4823e-01,  1.8630e-01,  7.8571e-02,  8.6420e-02,
          1.6211e-01,  2.2773e-01,  3.7879e-01, -4.2863e-02],
        [-3.6822e-01,  3.4729e-01, -1.0035e+00,  3.7297e-01, -2.6556e-01,
          1.2634e+00,  5.3275e-01, -6.7363e-01, -2.4373e-01],
        [ 1.8423e-02, -1.0546e+00,  2.8235e-01,  1.5534e+00, -4.1025e-01,
          5.2295e-02, -1.0160e+00,  6.7492e-01, -4.2652e-02],
        [ 3.7363e-02,  3.7727e-01,  3.1959e-01,  1.4271e-01,  1.7434e-01,
          1.3473e-01, -2.2928e-02,  3.1171e-02,  2.7626e-01],
        [ 7.0736e-02,  3.9380e-01,  1.1513e-01,  4.0939e-02,  1.1602e-01,
          1.5907e-01,  3.076

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([1964])) that is different to the input size (torch.Size([1964, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([1453])) that is different to the input size (torch.Size([1453, 1])) is deprecated. Please ensure they have the same size.



Epoch: 1 	 Train Loss: 0.7079798579216003 	 Validate_Accuracy: 0.583
epoch 2
Epoch: 2 	 Train Loss: 0.6861935555934906 	 Validate_Accuracy: 0.613
epoch 3
Epoch: 3 	 Train Loss: 0.6671153604984283 	 Validate_Accuracy: 0.7455
epoch 4
Epoch: 4 	 Train Loss: 0.6477271318435669 	 Validate_Accuracy: 0.784
epoch 5
Epoch: 5 	 Train Loss: 0.6182112693786621 	 Validate_Accuracy: 0.7875
epoch 6
Epoch: 6 	 Train Loss: 0.5837490260601044 	 Validate_Accuracy: 0.8145
epoch 7
Epoch: 7 	 Train Loss: 0.5406558811664581 	 Validate_Accuracy: 0.8165
epoch 8
Epoch: 8 	 Train Loss: 0.4961720257997513 	 Validate_Accuracy: 0.8125
epoch 9
Epoch: 9 	 Train Loss: 0.4576812833547592 	 Validate_Accuracy: 0.811
epoch 10
Epoch: 10 	 Train Loss: 0.43298742175102234 	 Validate_Accuracy: 0.8175
epoch 11
Epoch: 11 	 Train Loss: 0.41798868775367737 	 Validate_Accuracy: 0.8165
epoch 12
Epoch: 12 	 Train Loss: 0.4014259874820709 	 Validate_Accuracy: 0.8125
epoch 13
Epoch: 13 	 Train Loss: 0.386576846241951 	 Validate_Accura

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([2107])) that is different to the input size (torch.Size([2107, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([1223])) that is different to the input size (torch.Size([1223, 1])) is deprecated. Please ensure they have the same size.



Epoch: 1 	 Train Loss: 0.6970566213130951 	 Validate_Accuracy: 0.5015
epoch 2
Epoch: 2 	 Train Loss: 0.6934252679347992 	 Validate_Accuracy: 0.497
epoch 3
Epoch: 3 	 Train Loss: 0.6913086473941803 	 Validate_Accuracy: 0.626
epoch 4
Epoch: 4 	 Train Loss: 0.6797288060188293 	 Validate_Accuracy: 0.79
epoch 5
Epoch: 5 	 Train Loss: 0.6543748080730438 	 Validate_Accuracy: 0.6655
epoch 6
Epoch: 6 	 Train Loss: 0.6122320294380188 	 Validate_Accuracy: 0.8145
epoch 7
Epoch: 7 	 Train Loss: 0.5606295466423035 	 Validate_Accuracy: 0.814
epoch 8
Epoch: 8 	 Train Loss: 0.5149022042751312 	 Validate_Accuracy: 0.803
epoch 9
Epoch: 9 	 Train Loss: 0.4922853410243988 	 Validate_Accuracy: 0.792
epoch 10
Epoch: 10 	 Train Loss: 0.4778033345937729 	 Validate_Accuracy: 0.81
epoch 11
Epoch: 11 	 Train Loss: 0.4554288238286972 	 Validate_Accuracy: 0.819
epoch 12
Epoch: 12 	 Train Loss: 0.4366394132375717 	 Validate_Accuracy: 0.809
epoch 13
Epoch: 13 	 Train Loss: 0.4282867759466171 	 Validate_Accuracy: 0.81

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([917])) that is different to the input size (torch.Size([917, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([909])) that is different to the input size (torch.Size([909, 1])) is deprecated. Please ensure they have the same size.



Epoch: 2 	 Train Loss: 0.6715883761644363 	 Validate_Accuracy: 0.6175
epoch 3
Epoch: 3 	 Train Loss: 0.6312347948551178 	 Validate_Accuracy: 0.8065
epoch 4
Epoch: 4 	 Train Loss: 0.5710520297288895 	 Validate_Accuracy: 0.8245
epoch 5
Epoch: 5 	 Train Loss: 0.5095825344324112 	 Validate_Accuracy: 0.82
epoch 6
Epoch: 6 	 Train Loss: 0.46954426169395447 	 Validate_Accuracy: 0.821
epoch 7
Epoch: 7 	 Train Loss: 0.449299156665802 	 Validate_Accuracy: 0.817
epoch 8
Epoch: 8 	 Train Loss: 0.43195782601833344 	 Validate_Accuracy: 0.81
epoch 9
Epoch: 9 	 Train Loss: 0.4192747697234154 	 Validate_Accuracy: 0.8215
epoch 10
Epoch: 10 	 Train Loss: 0.4041189178824425 	 Validate_Accuracy: 0.8185
epoch 11
Epoch: 11 	 Train Loss: 0.3921358659863472 	 Validate_Accuracy: 0.832
epoch 12
Epoch: 12 	 Train Loss: 0.37875884026288986 	 Validate_Accuracy: 0.8355
epoch 13
Epoch: 13 	 Train Loss: 0.3695918917655945 	 Validate_Accuracy: 0.8415
epoch 14
Epoch: 14 	 Train Loss: 0.35786455124616623 	 Validate_Accur

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([3338])) that is different to the input size (torch.Size([3338, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([407])) that is different to the input size (torch.Size([407, 1])) is deprecated. Please ensure they have the same size.



Epoch: 1 	 Train Loss: 0.6956997513771057 	 Validate_Accuracy: 0.494
epoch 2
Epoch: 2 	 Train Loss: 0.6933992803096771 	 Validate_Accuracy: 0.497
epoch 3
Epoch: 3 	 Train Loss: 0.6970742642879486 	 Validate_Accuracy: 0.493
epoch 4
Epoch: 4 	 Train Loss: 0.6944491267204285 	 Validate_Accuracy: 0.503
epoch 5
Epoch: 5 	 Train Loss: 0.6963295340538025 	 Validate_Accuracy: 0.5235
epoch 6
Epoch: 6 	 Train Loss: 0.6944851577281952 	 Validate_Accuracy: 0.5105
epoch 7
Epoch: 7 	 Train Loss: 0.6936366558074951 	 Validate_Accuracy: 0.5385
epoch 8
Epoch: 8 	 Train Loss: 0.6932419538497925 	 Validate_Accuracy: 0.484
epoch 9
Epoch: 9 	 Train Loss: 0.6918240487575531 	 Validate_Accuracy: 0.4795
epoch 10
Epoch: 10 	 Train Loss: 0.6938412487506866 	 Validate_Accuracy: 0.481
epoch 11
Epoch: 11 	 Train Loss: 0.6909970045089722 	 Validate_Accuracy: 0.4805
epoch 12
Epoch: 12 	 Train Loss: 0.6911981403827667 	 Validate_Accuracy: 0.4955
epoch 13
Epoch: 13 	 Train Loss: 0.6911157369613647 	 Validate_Accuracy:

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([1080])) that is different to the input size (torch.Size([1080, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([286])) that is different to the input size (torch.Size([286, 1])) is deprecated. Please ensure they have the same size.



Epoch: 2 	 Train Loss: 0.6399931311607361 	 Validate_Accuracy: 0.7965
epoch 3
Epoch: 3 	 Train Loss: 0.5124683752655983 	 Validate_Accuracy: 0.8055
epoch 4
Epoch: 4 	 Train Loss: 0.4496164247393608 	 Validate_Accuracy: 0.8045
epoch 5
Epoch: 5 	 Train Loss: 0.4322058632969856 	 Validate_Accuracy: 0.8215
epoch 6
Epoch: 6 	 Train Loss: 0.3992621526122093 	 Validate_Accuracy: 0.824
epoch 7
Epoch: 7 	 Train Loss: 0.3920150548219681 	 Validate_Accuracy: 0.8225
epoch 8
Epoch: 8 	 Train Loss: 0.3778050094842911 	 Validate_Accuracy: 0.841
epoch 9
Epoch: 9 	 Train Loss: 0.3432097062468529 	 Validate_Accuracy: 0.8525
epoch 10
Epoch: 10 	 Train Loss: 0.34034405648708344 	 Validate_Accuracy: 0.849
epoch 11
Epoch: 11 	 Train Loss: 0.3286140188574791 	 Validate_Accuracy: 0.849
epoch 12
Epoch: 12 	 Train Loss: 0.3261665031313896 	 Validate_Accuracy: 0.85
epoch 13
Epoch: 13 	 Train Loss: 0.31236570328474045 	 Validate_Accuracy: 0.846
epoch 14
Epoch: 14 	 Train Loss: 0.3366278260946274 	 Validate_Accura

[INFO 08-29 04:52:45] ax.service.managed_loop: Running optimization trial 6...


Epoch: 111 	 Train Loss: 0.26860594749450684 	 Validate_Accuracy: 0.857
model parameters! 

conv1.weight tensor([[[[-0.2543, -0.1934, -0.3063],
          [-0.0814,  0.0530, -0.0588],
          [-0.2725, -0.0909, -0.1425]]]])
conv1.bias tensor([0.0042])
first_linear.weight tensor([[ 9.9509e-01, -1.4198e+00,  1.6349e+00, -3.6961e-01, -5.1542e-02,
         -7.9767e-01,  1.8320e-01,  1.6811e-03,  4.3511e-01],
        [ 9.4989e-02, -3.6178e-01, -2.1237e-01,  2.4430e-01, -7.5957e-01,
         -9.5168e-01, -3.1932e-01,  5.2917e-02, -8.9777e-01],
        [-5.6234e-01, -8.6204e-04,  5.5793e-01, -7.8152e-01, -7.2910e-01,
          4.9552e-02, -6.7986e-01, -5.8232e-01, -2.2806e-01],
        [ 4.0933e-01, -1.2113e-01,  6.0503e-01,  1.0441e+00, -9.0990e-01,
          2.8873e-01, -1.0358e+00,  1.2046e+00,  6.0252e-02],
        [ 3.0656e-02,  1.8295e-01,  7.8450e-01,  1.8653e-01, -6.6158e-02,
          8.6879e-01,  2.8617e-01,  7.3143e-01,  7.5385e-01],
        [ 8.7929e-01, -1.4448e-01,  1.6574e-01,

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([2568])) that is different to the input size (torch.Size([2568, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([908])) that is different to the input size (torch.Size([908, 1])) is deprecated. Please ensure they have the same size.



Epoch: 2 	 Train Loss: 0.6929388344287872 	 Validate_Accuracy: 0.4995
epoch 3
Epoch: 3 	 Train Loss: 0.6926884055137634 	 Validate_Accuracy: 0.558
epoch 4
Epoch: 4 	 Train Loss: 0.6897078156471252 	 Validate_Accuracy: 0.5325
epoch 5
Epoch: 5 	 Train Loss: 0.6856678426265717 	 Validate_Accuracy: 0.5615
epoch 6
Epoch: 6 	 Train Loss: 0.6771183907985687 	 Validate_Accuracy: 0.5935
epoch 7
Epoch: 7 	 Train Loss: 0.6573483049869537 	 Validate_Accuracy: 0.7035
epoch 8
Epoch: 8 	 Train Loss: 0.6234309673309326 	 Validate_Accuracy: 0.781
epoch 9
Epoch: 9 	 Train Loss: 0.5778015851974487 	 Validate_Accuracy: 0.81
epoch 10
Epoch: 10 	 Train Loss: 0.5273618996143341 	 Validate_Accuracy: 0.8215
epoch 11
Epoch: 11 	 Train Loss: 0.4749194532632828 	 Validate_Accuracy: 0.823
epoch 12
Epoch: 12 	 Train Loss: 0.4229704439640045 	 Validate_Accuracy: 0.822
epoch 13
Epoch: 13 	 Train Loss: 0.39782728254795074 	 Validate_Accuracy: 0.8305
epoch 14
Epoch: 14 	 Train Loss: 0.3908500373363495 	 Validate_Accura

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([1537])) that is different to the input size (torch.Size([1537, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([738])) that is different to the input size (torch.Size([738, 1])) is deprecated. Please ensure they have the same size.



Epoch: 1 	 Train Loss: 0.6963546474774679 	 Validate_Accuracy: 0.503
epoch 2
Epoch: 2 	 Train Loss: 0.6929350892702738 	 Validate_Accuracy: 0.467
epoch 3
Epoch: 3 	 Train Loss: 0.6932532787322998 	 Validate_Accuracy: 0.5045
epoch 4
Epoch: 4 	 Train Loss: 0.6921535134315491 	 Validate_Accuracy: 0.4635
epoch 5
Epoch: 5 	 Train Loss: 0.6923534274101257 	 Validate_Accuracy: 0.484
epoch 6
Epoch: 6 	 Train Loss: 0.6921993096669515 	 Validate_Accuracy: 0.4995
epoch 7
Epoch: 7 	 Train Loss: 0.6922433177630106 	 Validate_Accuracy: 0.514
epoch 8
Epoch: 8 	 Train Loss: 0.6916840473810831 	 Validate_Accuracy: 0.4745
epoch 9
Epoch: 9 	 Train Loss: 0.6913769443829855 	 Validate_Accuracy: 0.5155
epoch 10
Epoch: 10 	 Train Loss: 0.6912450393040975 	 Validate_Accuracy: 0.567
epoch 11
Epoch: 11 	 Train Loss: 0.6907891432444254 	 Validate_Accuracy: 0.5275
epoch 12
Epoch: 12 	 Train Loss: 0.6893025437990824 	 Validate_Accuracy: 0.514
epoch 13
Epoch: 13 	 Train Loss: 0.6830681165059408 	 Validate_Accuracy:

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([1566])) that is different to the input size (torch.Size([1566, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([797])) that is different to the input size (torch.Size([797, 1])) is deprecated. Please ensure they have the same size.



epoch 2
Epoch: 2 	 Train Loss: 0.6931565403938293 	 Validate_Accuracy: 0.511
epoch 3
Epoch: 3 	 Train Loss: 0.6927517056465149 	 Validate_Accuracy: 0.5345
epoch 4
Epoch: 4 	 Train Loss: 0.6926664710044861 	 Validate_Accuracy: 0.549
epoch 5
Epoch: 5 	 Train Loss: 0.6910472214221954 	 Validate_Accuracy: 0.5505
epoch 6
Epoch: 6 	 Train Loss: 0.6892112791538239 	 Validate_Accuracy: 0.5785
epoch 7
Epoch: 7 	 Train Loss: 0.686807781457901 	 Validate_Accuracy: 0.5845
epoch 8
Epoch: 8 	 Train Loss: 0.6820991337299347 	 Validate_Accuracy: 0.5855
epoch 9
Epoch: 9 	 Train Loss: 0.6761163771152496 	 Validate_Accuracy: 0.59
epoch 10
Epoch: 10 	 Train Loss: 0.6683769226074219 	 Validate_Accuracy: 0.608
epoch 11
Epoch: 11 	 Train Loss: 0.6583583950996399 	 Validate_Accuracy: 0.621
epoch 12
Epoch: 12 	 Train Loss: 0.6472035050392151 	 Validate_Accuracy: 0.6335
epoch 13
Epoch: 13 	 Train Loss: 0.6317122876644135 	 Validate_Accuracy: 0.6525
epoch 14
Epoch: 14 	 Train Loss: 0.6168273389339447 	 Validate_

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([2987])) that is different to the input size (torch.Size([2987, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([23])) that is different to the input size (torch.Size([23, 1])) is deprecated. Please ensure they have the same size.



Epoch: 1 	 Train Loss: 0.6824726760387421 	 Validate_Accuracy: 0.503
epoch 2
Epoch: 2 	 Train Loss: 0.709624707698822 	 Validate_Accuracy: 0.502
epoch 3
Epoch: 3 	 Train Loss: 0.7031049132347107 	 Validate_Accuracy: 0.4385
epoch 4
Epoch: 4 	 Train Loss: 0.6944516897201538 	 Validate_Accuracy: 0.5565
epoch 5
Epoch: 5 	 Train Loss: 0.6823127865791321 	 Validate_Accuracy: 0.5115
epoch 6
Epoch: 6 	 Train Loss: 0.6832369863986969 	 Validate_Accuracy: 0.5125
epoch 7
Epoch: 7 	 Train Loss: 0.729634165763855 	 Validate_Accuracy: 0.5135
epoch 8
Epoch: 8 	 Train Loss: 0.7027681171894073 	 Validate_Accuracy: 0.534
epoch 9
Epoch: 9 	 Train Loss: 0.687533438205719 	 Validate_Accuracy: 0.573
epoch 10
Epoch: 10 	 Train Loss: 0.6915014982223511 	 Validate_Accuracy: 0.552
epoch 11
Epoch: 11 	 Train Loss: 0.6909596025943756 	 Validate_Accuracy: 0.4685
epoch 12
Epoch: 12 	 Train Loss: 0.684865802526474 	 Validate_Accuracy: 0.6225
epoch 13
Epoch: 13 	 Train Loss: 0.6641985177993774 	 Validate_Accuracy: 0.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([2925])) that is different to the input size (torch.Size([2925, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([1055])) that is different to the input size (torch.Size([1055, 1])) is deprecated. Please ensure they have the same size.



Epoch: 2 	 Train Loss: 0.692890465259552 	 Validate_Accuracy: 0.498
epoch 3
Epoch: 3 	 Train Loss: 0.7000684142112732 	 Validate_Accuracy: 0.496
epoch 4
Epoch: 4 	 Train Loss: 0.6948840320110321 	 Validate_Accuracy: 0.5565
epoch 5
Epoch: 5 	 Train Loss: 0.6941920518875122 	 Validate_Accuracy: 0.594
epoch 6
Epoch: 6 	 Train Loss: 0.6883808672428131 	 Validate_Accuracy: 0.5715
epoch 7
Epoch: 7 	 Train Loss: 0.6818545758724213 	 Validate_Accuracy: 0.5605
epoch 8
Epoch: 8 	 Train Loss: 0.676396369934082 	 Validate_Accuracy: 0.5875
epoch 9
Epoch: 9 	 Train Loss: 0.6602209210395813 	 Validate_Accuracy: 0.638
epoch 10
Epoch: 10 	 Train Loss: 0.6386017203330994 	 Validate_Accuracy: 0.6455
epoch 11
Epoch: 11 	 Train Loss: 0.6154312789440155 	 Validate_Accuracy: 0.644
epoch 12
Epoch: 12 	 Train Loss: 0.5820437371730804 	 Validate_Accuracy: 0.773
epoch 13
Epoch: 13 	 Train Loss: 0.5573694407939911 	 Validate_Accuracy: 0.7945
epoch 14
Epoch: 14 	 Train Loss: 0.5296034514904022 	 Validate_Accuracy:

[INFO 08-29 04:54:57] ax.service.managed_loop: Running optimization trial 7...


Epoch: 170 	 Train Loss: 0.2149822860956192 	 Validate_Accuracy: 0.8775
model parameters! 

conv1.weight tensor([[[[-0.1135, -0.0510, -0.1311],
          [-0.0473, -0.0007, -0.0401],
          [-0.1127, -0.0382, -0.1217]]]])
conv1.bias tensor([0.0529])
first_linear.weight tensor([[-0.3048,  0.5040, -0.8363,  0.2056, -0.6515,  1.6392,  0.5418, -0.5786,
         -0.3359],
        [ 0.0392, -0.0097,  0.2556,  0.0790,  0.2364,  0.3961,  0.1564, -0.0389,
          0.2901],
        [ 0.2532,  0.4716,  0.2988,  0.1791,  0.2823, -0.0241,  0.0632,  0.0159,
          0.1322],
        [-0.3123, -0.4518,  0.1548, -0.1027, -0.1721, -0.2983, -0.2833, -0.1477,
          0.0298],
        [-0.7189,  0.1518,  0.2733,  1.4291, -0.4968, -0.4648, -0.7568,  0.0045,
          0.3763],
        [ 0.2184,  0.1362, -0.1450,  1.0131, -1.0833,  0.8786, -0.8525,  1.6878,
         -0.9503],
        [ 0.7321, -1.8668,  0.6041, -0.1708,  0.4348,  0.1146, -0.2390,  0.0853,
         -0.2233],
        [ 0.1283,  0.3147, 

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([1848])) that is different to the input size (torch.Size([1848, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([1447])) that is different to the input size (torch.Size([1447, 1])) is deprecated. Please ensure they have the same size.



Epoch: 2 	 Train Loss: 0.6925258040428162 	 Validate_Accuracy: 0.4965
epoch 3
Epoch: 3 	 Train Loss: 0.6946051716804504 	 Validate_Accuracy: 0.497
epoch 4
Epoch: 4 	 Train Loss: 0.6940310299396515 	 Validate_Accuracy: 0.496
epoch 5
Epoch: 5 	 Train Loss: 0.6928571462631226 	 Validate_Accuracy: 0.513
epoch 6
Epoch: 6 	 Train Loss: 0.6927207708358765 	 Validate_Accuracy: 0.5065
epoch 7
Epoch: 7 	 Train Loss: 0.692971259355545 	 Validate_Accuracy: 0.5025
epoch 8
Epoch: 8 	 Train Loss: 0.6926013231277466 	 Validate_Accuracy: 0.5045
epoch 9
Epoch: 9 	 Train Loss: 0.6923686265945435 	 Validate_Accuracy: 0.53
epoch 10
Epoch: 10 	 Train Loss: 0.6925238370895386 	 Validate_Accuracy: 0.5155
epoch 11
Epoch: 11 	 Train Loss: 0.6926269829273224 	 Validate_Accuracy: 0.517
epoch 12
Epoch: 12 	 Train Loss: 0.6924044489860535 	 Validate_Accuracy: 0.534
epoch 13
Epoch: 13 	 Train Loss: 0.6921006143093109 	 Validate_Accuracy: 0.4855
epoch 14
Epoch: 14 	 Train Loss: 0.691938042640686 	 Validate_Accuracy: 

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([2541])) that is different to the input size (torch.Size([2541, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([1525])) that is different to the input size (torch.Size([1525, 1])) is deprecated. Please ensure they have the same size.



Epoch: 2 	 Train Loss: 0.6941915452480316 	 Validate_Accuracy: 0.497
epoch 3
Epoch: 3 	 Train Loss: 0.6933342814445496 	 Validate_Accuracy: 0.503
epoch 4
Epoch: 4 	 Train Loss: 0.693218857049942 	 Validate_Accuracy: 0.4465
epoch 5
Epoch: 5 	 Train Loss: 0.6931290030479431 	 Validate_Accuracy: 0.494
epoch 6
Epoch: 6 	 Train Loss: 0.6931050717830658 	 Validate_Accuracy: 0.497
epoch 7
Epoch: 7 	 Train Loss: 0.693179577589035 	 Validate_Accuracy: 0.497
epoch 8
Epoch: 8 	 Train Loss: 0.693174809217453 	 Validate_Accuracy: 0.503
epoch 9
Epoch: 9 	 Train Loss: 0.693169504404068 	 Validate_Accuracy: 0.5085
epoch 10
Epoch: 10 	 Train Loss: 0.6931382715702057 	 Validate_Accuracy: 0.503
epoch 11
Epoch: 11 	 Train Loss: 0.6932027041912079 	 Validate_Accuracy: 0.503
epoch 12
Epoch: 12 	 Train Loss: 0.6931695938110352 	 Validate_Accuracy: 0.5
epoch 13
Epoch: 13 	 Train Loss: 0.6931570768356323 	 Validate_Accuracy: 0.497
epoch 14
Epoch: 14 	 Train Loss: 0.693150520324707 	 Validate_Accuracy: 0.497
ep

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([1949])) that is different to the input size (torch.Size([1949, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([1675])) that is different to the input size (torch.Size([1675, 1])) is deprecated. Please ensure they have the same size.



Epoch: 1 	 Train Loss: 0.6932500004768372 	 Validate_Accuracy: 0.5345
epoch 2
Epoch: 2 	 Train Loss: 0.6888712346553802 	 Validate_Accuracy: 0.5
epoch 3
Epoch: 3 	 Train Loss: 0.6816347241401672 	 Validate_Accuracy: 0.541
epoch 4
Epoch: 4 	 Train Loss: 0.6640518009662628 	 Validate_Accuracy: 0.68
epoch 5
Epoch: 5 	 Train Loss: 0.6387974917888641 	 Validate_Accuracy: 0.7245
epoch 6
Epoch: 6 	 Train Loss: 0.5981154143810272 	 Validate_Accuracy: 0.751
epoch 7
Epoch: 7 	 Train Loss: 0.5524817109107971 	 Validate_Accuracy: 0.7805
epoch 8
Epoch: 8 	 Train Loss: 0.5009320676326752 	 Validate_Accuracy: 0.795
epoch 9
Epoch: 9 	 Train Loss: 0.4545120447874069 	 Validate_Accuracy: 0.8075
epoch 10
Epoch: 10 	 Train Loss: 0.41921354830265045 	 Validate_Accuracy: 0.8155
epoch 11
Epoch: 11 	 Train Loss: 0.39772625267505646 	 Validate_Accuracy: 0.8135
epoch 12
Epoch: 12 	 Train Loss: 0.3844502866268158 	 Validate_Accuracy: 0.8085
epoch 13
Epoch: 13 	 Train Loss: 0.3781917989253998 	 Validate_Accuracy:

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([1918])) that is different to the input size (torch.Size([1918, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([322])) that is different to the input size (torch.Size([322, 1])) is deprecated. Please ensure they have the same size.



Epoch: 2 	 Train Loss: 0.6925364931424459 	 Validate_Accuracy: 0.5035
epoch 3
Epoch: 3 	 Train Loss: 0.695292075475057 	 Validate_Accuracy: 0.4955
epoch 4
Epoch: 4 	 Train Loss: 0.6930740078290304 	 Validate_Accuracy: 0.4895
epoch 5
Epoch: 5 	 Train Loss: 0.6933409372965494 	 Validate_Accuracy: 0.499
epoch 6
Epoch: 6 	 Train Loss: 0.6925608913103739 	 Validate_Accuracy: 0.5115
epoch 7
Epoch: 7 	 Train Loss: 0.6918178002039591 	 Validate_Accuracy: 0.4925
epoch 8
Epoch: 8 	 Train Loss: 0.6918812990188599 	 Validate_Accuracy: 0.4845
epoch 9
Epoch: 9 	 Train Loss: 0.6910069187482198 	 Validate_Accuracy: 0.511
epoch 10
Epoch: 10 	 Train Loss: 0.6886135141054789 	 Validate_Accuracy: 0.531
epoch 11
Epoch: 11 	 Train Loss: 0.6853172183036804 	 Validate_Accuracy: 0.56
epoch 12
Epoch: 12 	 Train Loss: 0.6828149358431498 	 Validate_Accuracy: 0.602
epoch 13
Epoch: 13 	 Train Loss: 0.6630253593126932 	 Validate_Accuracy: 0.7045
epoch 14
Epoch: 14 	 Train Loss: 0.6286829511324564 	 Validate_Accuracy

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([2309])) that is different to the input size (torch.Size([2309, 1])) is deprecated. Please ensure they have the same size.



Epoch: 3 	 Train Loss: 0.6931222677230835 	 Validate_Accuracy: 0.5115
epoch 4
Epoch: 4 	 Train Loss: 0.6923925280570984 	 Validate_Accuracy: 0.516
epoch 5
Epoch: 5 	 Train Loss: 0.6924601793289185 	 Validate_Accuracy: 0.5185
epoch 6
Epoch: 6 	 Train Loss: 0.6924355626106262 	 Validate_Accuracy: 0.4995
epoch 7
Epoch: 7 	 Train Loss: 0.691952645778656 	 Validate_Accuracy: 0.4605
epoch 8
Epoch: 8 	 Train Loss: 0.69105064868927 	 Validate_Accuracy: 0.466
epoch 9
Epoch: 9 	 Train Loss: 0.6898775696754456 	 Validate_Accuracy: 0.479
epoch 10
Epoch: 10 	 Train Loss: 0.688535749912262 	 Validate_Accuracy: 0.4945
epoch 11
Epoch: 11 	 Train Loss: 0.6870445013046265 	 Validate_Accuracy: 0.518
epoch 12
Epoch: 12 	 Train Loss: 0.6853300333023071 	 Validate_Accuracy: 0.538
epoch 13
Epoch: 13 	 Train Loss: 0.683255672454834 	 Validate_Accuracy: 0.5505
epoch 14
Epoch: 14 	 Train Loss: 0.6806706190109253 	 Validate_Accuracy: 0.5575
epoch 15
Epoch: 15 	 Train Loss: 0.6774618625640869 	 Validate_Accuracy:

[INFO 08-29 04:57:15] ax.service.managed_loop: Running optimization trial 8...


Epoch: 242 	 Train Loss: 0.19777637720108032 	 Validate_Accuracy: 0.89
epoch 243
Epoch: 243 	 Train Loss: 0.19750283658504486 	 Validate_Accuracy: 0.8905
model parameters! 

conv1.weight tensor([[[[ 0.1322,  0.0541,  0.1804],
          [ 0.0816, -0.0078,  0.0553],
          [ 0.1306,  0.0389,  0.1701]]]])
conv1.bias tensor([-0.0740])
first_linear.weight tensor([[ 0.2347,  0.1755, -0.5483, -0.6577,  0.9013,  0.3845,  0.1335, -0.2598,
         -0.0707],
        [ 0.3960,  0.2303,  0.1437, -0.0758,  0.4074,  0.4668,  0.2596,  0.1019,
          0.1069],
        [-0.2735, -0.4181, -0.1838,  1.3452, -0.6502,  0.7070, -0.4228,  0.1218,
         -0.2435],
        [ 0.1565, -0.0329,  0.0324,  0.0170,  0.1007,  0.2624,  0.0800,  0.1904,
          0.0267],
        [-0.7871,  1.1368, -0.5226,  1.0808, -0.4981,  0.0866, -0.3655,  0.0958,
         -0.0275],
        [ 0.0745,  0.0451,  0.4692,  0.2442, -0.5961, -0.5447, -0.7652,  1.2989,
         -0.1641],
        [-0.4742,  1.1893, -0.6705, -0.4517,

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([1828])) that is different to the input size (torch.Size([1828, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([207])) that is different to the input size (torch.Size([207, 1])) is deprecated. Please ensure they have the same size.



Epoch: 2 	 Train Loss: 0.6895996332168579 	 Validate_Accuracy: 0.454
epoch 3
Epoch: 3 	 Train Loss: 0.6837972601254781 	 Validate_Accuracy: 0.5275
epoch 4
Epoch: 4 	 Train Loss: 0.6751007040341696 	 Validate_Accuracy: 0.5895
epoch 5
Epoch: 5 	 Train Loss: 0.6543176770210266 	 Validate_Accuracy: 0.7435
epoch 6
Epoch: 6 	 Train Loss: 0.6348650654157003 	 Validate_Accuracy: 0.785
epoch 7
Epoch: 7 	 Train Loss: 0.6078921755154928 	 Validate_Accuracy: 0.798
epoch 8
Epoch: 8 	 Train Loss: 0.5672086079915365 	 Validate_Accuracy: 0.8175
epoch 9
Epoch: 9 	 Train Loss: 0.5439449350039164 	 Validate_Accuracy: 0.817
epoch 10
Epoch: 10 	 Train Loss: 0.5016112228234609 	 Validate_Accuracy: 0.8185
epoch 11
Epoch: 11 	 Train Loss: 0.47978221376736957 	 Validate_Accuracy: 0.8135
epoch 12
Epoch: 12 	 Train Loss: 0.47996848821640015 	 Validate_Accuracy: 0.81
epoch 13
Epoch: 13 	 Train Loss: 0.46595872441927594 	 Validate_Accuracy: 0.811
epoch 14
Epoch: 14 	 Train Loss: 0.46049246191978455 	 Validate_Accu

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([2257])) that is different to the input size (torch.Size([2257, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([241])) that is different to the input size (torch.Size([241, 1])) is deprecated. Please ensure they have the same size.



Epoch: 1 	 Train Loss: 0.7384031414985657 	 Validate_Accuracy: 0.503
epoch 2
Epoch: 2 	 Train Loss: 0.7153958976268768 	 Validate_Accuracy: 0.503
epoch 3
Epoch: 3 	 Train Loss: 0.7082675993442535 	 Validate_Accuracy: 0.503
epoch 4
Epoch: 4 	 Train Loss: 0.7077440619468689 	 Validate_Accuracy: 0.503
epoch 5
Epoch: 5 	 Train Loss: 0.7018306851387024 	 Validate_Accuracy: 0.503
epoch 6
Epoch: 6 	 Train Loss: 0.6949267685413361 	 Validate_Accuracy: 0.481
epoch 7
Epoch: 7 	 Train Loss: 0.6910946369171143 	 Validate_Accuracy: 0.524
epoch 8
Epoch: 8 	 Train Loss: 0.68907031416893 	 Validate_Accuracy: 0.5305
epoch 9
Epoch: 9 	 Train Loss: 0.6904495060443878 	 Validate_Accuracy: 0.5495
epoch 10
Epoch: 10 	 Train Loss: 0.6872432231903076 	 Validate_Accuracy: 0.5835
epoch 11
Epoch: 11 	 Train Loss: 0.6867666244506836 	 Validate_Accuracy: 0.594
epoch 12
Epoch: 12 	 Train Loss: 0.6847354769706726 	 Validate_Accuracy: 0.5965
epoch 13
Epoch: 13 	 Train Loss: 0.6822404265403748 	 Validate_Accuracy: 0.5

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([1463])) that is different to the input size (torch.Size([1463, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([1294])) that is different to the input size (torch.Size([1294, 1])) is deprecated. Please ensure they have the same size.



Epoch: 1 	 Train Loss: 0.6939660906791687 	 Validate_Accuracy: 0.4745
epoch 2
Epoch: 2 	 Train Loss: 0.6867953836917877 	 Validate_Accuracy: 0.545
epoch 3
Epoch: 3 	 Train Loss: 0.6760939657688141 	 Validate_Accuracy: 0.591
epoch 4
Epoch: 4 	 Train Loss: 0.6601088047027588 	 Validate_Accuracy: 0.746
epoch 5
Epoch: 5 	 Train Loss: 0.6356361508369446 	 Validate_Accuracy: 0.8005
epoch 6
Epoch: 6 	 Train Loss: 0.6026951968669891 	 Validate_Accuracy: 0.8095
epoch 7
Epoch: 7 	 Train Loss: 0.5658406615257263 	 Validate_Accuracy: 0.8165
epoch 8
Epoch: 8 	 Train Loss: 0.5281037390232086 	 Validate_Accuracy: 0.8195
epoch 9
Epoch: 9 	 Train Loss: 0.4904510825872421 	 Validate_Accuracy: 0.821
epoch 10
Epoch: 10 	 Train Loss: 0.45811907947063446 	 Validate_Accuracy: 0.812
epoch 11
Epoch: 11 	 Train Loss: 0.4330664128065109 	 Validate_Accuracy: 0.8255
epoch 12
Epoch: 12 	 Train Loss: 0.4152846485376358 	 Validate_Accuracy: 0.8205
epoch 13
Epoch: 13 	 Train Loss: 0.40175390243530273 	 Validate_Accura

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([2106])) that is different to the input size (torch.Size([2106, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([1884])) that is different to the input size (torch.Size([1884, 1])) is deprecated. Please ensure they have the same size.



Epoch: 2 	 Train Loss: 0.7087441682815552 	 Validate_Accuracy: 0.503
epoch 3
Epoch: 3 	 Train Loss: 0.7046214938163757 	 Validate_Accuracy: 0.503
epoch 4
Epoch: 4 	 Train Loss: 0.7011540532112122 	 Validate_Accuracy: 0.503
epoch 5
Epoch: 5 	 Train Loss: 0.6985942721366882 	 Validate_Accuracy: 0.503
epoch 6
Epoch: 6 	 Train Loss: 0.6967005729675293 	 Validate_Accuracy: 0.497
epoch 7
Epoch: 7 	 Train Loss: 0.6951795220375061 	 Validate_Accuracy: 0.5105
epoch 8
Epoch: 8 	 Train Loss: 0.6941710412502289 	 Validate_Accuracy: 0.5245
epoch 9
Epoch: 9 	 Train Loss: 0.6935839653015137 	 Validate_Accuracy: 0.517
epoch 10
Epoch: 10 	 Train Loss: 0.6931160688400269 	 Validate_Accuracy: 0.4895
epoch 11
Epoch: 11 	 Train Loss: 0.6929435133934021 	 Validate_Accuracy: 0.482
epoch 12
Epoch: 12 	 Train Loss: 0.6928936541080475 	 Validate_Accuracy: 0.4985
epoch 13
Epoch: 13 	 Train Loss: 0.692970871925354 	 Validate_Accuracy: 0.5135
epoch 14
Epoch: 14 	 Train Loss: 0.6928998827934265 	 Validate_Accuracy:

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([1419])) that is different to the input size (torch.Size([1419, 1])) is deprecated. Please ensure they have the same size.

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:498: UserWarning:

Using a target size (torch.Size([1016])) that is different to the input size (torch.Size([1016, 1])) is deprecated. Please ensure they have the same size.



Epoch: 1 	 Train Loss: 0.7243368029594421 	 Validate_Accuracy: 0.516
epoch 2
Epoch: 2 	 Train Loss: 0.6949010888735453 	 Validate_Accuracy: 0.4415
epoch 3
Epoch: 3 	 Train Loss: 0.663761556148529 	 Validate_Accuracy: 0.596
epoch 4
Epoch: 4 	 Train Loss: 0.6453800996144613 	 Validate_Accuracy: 0.684
epoch 5
Epoch: 5 	 Train Loss: 0.5827124118804932 	 Validate_Accuracy: 0.763
epoch 6
Epoch: 6 	 Train Loss: 0.5273489554723104 	 Validate_Accuracy: 0.7895
epoch 7
Epoch: 7 	 Train Loss: 0.4799172580242157 	 Validate_Accuracy: 0.797
epoch 8
Epoch: 8 	 Train Loss: 0.44087935487429303 	 Validate_Accuracy: 0.802
epoch 9
Epoch: 9 	 Train Loss: 0.41204263766606647 	 Validate_Accuracy: 0.8065
epoch 10
Epoch: 10 	 Train Loss: 0.3975741962591807 	 Validate_Accuracy: 0.8055
epoch 11
Epoch: 11 	 Train Loss: 0.38075260321299237 	 Validate_Accuracy: 0.816
epoch 12
Epoch: 12 	 Train Loss: 0.37641750772794086 	 Validate_Accuracy: 0.8205
epoch 13
Epoch: 13 	 Train Loss: 0.36411140362421673 	 Validate_Accura

[INFO 08-29 04:59:55] ax.service.managed_loop: Running optimization trial 9...


Epoch: 250 	 Train Loss: 0.23374617099761963 	 Validate_Accuracy: 0.8765
model parameters! 

conv1.weight tensor([[[[ 0.2129,  0.0241,  0.2804],
          [ 0.0543, -0.0136,  0.0703],
          [ 0.2549,  0.0870,  0.2505]]]])
conv1.bias tensor([-0.0720])
first_linear.weight tensor([[ 0.8521, -0.4787,  0.2435, -0.1044, -0.6683,  0.5277, -0.5835,  1.5780,
         -0.8038],
        [-0.4190,  0.1715, -0.2043,  0.3390,  1.6610, -0.1174,  0.3284,  0.7539,
          0.0430],
        [ 0.5420, -0.6766,  0.1462, -0.9829,  1.0317,  0.1476,  1.1427, -1.6068,
          0.7493],
        [-0.8120,  1.7491, -0.9967, -0.0960, -0.9365,  1.0114,  0.5385, -0.0662,
         -0.2262],
        [ 0.4533,  0.4099,  0.5010,  0.2191,  0.9822,  0.8834, -0.0177, -0.0304,
         -0.1492],
        [ 0.5229,  0.3699,  1.3970, -0.1383, -0.8942,  0.1337,  0.7386, -0.3382,
          1.5705],
        [ 0.8914,  0.2953, -0.4049, -2.5576,  0.4692,  0.1996,  0.9908, -0.0998,
         -0.3886],
        [-0.6769,  0.4191

In [0]:
!ls /usr/local/lib/python3.6/dist-packages/botorch/

ls: cannot access '/usr/local/lib/python3.6/dist-packages/botorch/': No such file or directory


In [11]:
with open('hyperparameters.pl', 'rb') as f:
    x = pickle.load(f)

EOFError: ignored

In [10]:
objects

[]