In [0]:
# 

# !pip install -U --target=/usr/local/lib/python3.6/dist-packages git+https://github.com/pytorch/botorch.git

# !pip install -U -q torch==1.2.0 torchvision

# !pip install -U scikit-learn
# !pip install -U --target=/usr/local/lib/python3.6/dist-packages git+https://github.com/anhhuyalex/Ax.git
  
!pip install -U --target=/usr/local/lib/python3.6/dist-packages git+https://github.com/anhhuyalex/Ax.git
  
%cd /content
# %cd /usr/local/lib/python3.6/dist-packages
!rm -rf botorch
%cd /content
!git clone https://github.com/pytorch/botorch.git
%cd botorch
!pip install .

!pip install sqlalchemy

  Cloning https://github.com/anhhuyalex/Ax.git to /tmp/pip-req-build-5dgscdim
  Running command git clone -q https://github.com/anhhuyalex/Ax.git /tmp/pip-req-build-5dgscdim
     |████████████████████████████████| 174kB 6.8MB/s 
     |████████████████████████████████| 133kB 49.1MB/s 
     |████████████████████████████████| 10.5MB 45.1MB/s 
     |████████████████████████████████| 25.2MB 1.7MB/s 
     |████████████████████████████████| 7.1MB 34.7MB/s 
     |████████████████████████████████| 748.9MB 20kB/s 
     |████████████████████████████████| 215kB 44.7MB/s 
     |████████████████████████████████| 512kB 38.2MB/s 
     |████████████████████████████████| 20.4MB 33.5MB/s 
     |████████████████████████████████| 235kB 40.6MB/s 
     |████████████████████████████████| 6.7MB 26.0MB/s 
     |████████████████████████████████| 286kB 43.8MB/s 
  Created wheel for ax-platform: filename=ax_platform-0.1.4-cp36-cp36m-linux_x86_64.whl size=918268 sha256=22f2074486e517c35b8facf19d1eca0b96bfd14c22fb38

/content
/content
Cloning into 'botorch'...
remote: Enumerating objects: 253, done.
remote: Counting objects: 100% (253/253), done.
remote: Compressing objects: 100% (176/176), done.
remote: Total 5949 (delta 100), reused 124 (delta 39), pack-reused 5696
Receiving objects: 100% (5949/5949), 10.53 MiB | 13.34 MiB/s, done.
Resolving deltas: 100% (3798/3798), done.
/content/botorch
Processing /content/botorch
  Created wheel for botorch: filename=botorch-0.1.3-cp36-none-any.whl size=175135 sha256=c2593e26597db0fa30a4ef590d30367c1b0bd6553995a2904e511b4d1ee38e0a
  Stored in directory: /tmp/pip-ephem-wheel-cache-i5p0tlr6/wheels/d8/0e/3f/502176509633fec729eabc1a42e465b3603faf0c30b4782f33
Successfully built botorch
  Found existing installation: botorch 0.1.3
    Uninstalling botorch-0.1.3:
      Successfully uninstalled botorch-0.1.3


In [0]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
%cd /content/
!git clone https://github.com/anhhuyalex/renormalization.git
!cp /content/drive/My\ Drive/Year\ 4\:\ Synthesis/NS162\:\ Statistical\ Mechanics/Renormalization\ Research\ Project/renormalization/supervised_convnet/t_2.269/3x3/ising81x81_temp2.269_uncorrelated9x9.npy /content/renormalization/supervised_convnet/t_2.269/3x3
!cp /content/drive/My\ Drive/Year\ 4\:\ Synthesis/NS162\:\ Statistical\ Mechanics/Renormalization\ Research\ Project/renormalization/supervised_convnet/t_2.269/ising81x81_temp2.269.npy /content/renormalization/supervised_convnet/t_2.269      

/content
Cloning into 'renormalization'...
remote: Enumerating objects: 260, done.
remote: Counting objects: 100% (260/260), done.
remote: Compressing objects: 100% (144/144), done.
remote: Total 260 (delta 149), reused 211 (delta 100), pack-reused 0
Receiving objects: 100% (260/260), 588.31 KiB | 1.63 MiB/s, done.
Resolving deltas: 100% (149/149), done.


In [0]:
%cd /content/renormalization/supervised_convnet/t_2.269/3x3
import torch
import numpy as np
import pickle


from ax import RangeParameter, ParameterType
from ax.service.ax_client import AxClient
from ax.plot.contour import plot_contour
from ax.plot.trace import optimization_trace_single_method
from ax.service.managed_loop import optimize
from ax.utils.notebook.plotting import render, init_notebook_plotting

import sys
import time
sys.path.insert(0, "../../")
import supervised_convnet
import train, frozen


/content/renormalization/supervised_convnet/t_2.269/3x3
Uncorrelated [[ 1  1  1 -1 -1 -1  1 -1 -1]
 [ 1  1  1 -1 -1 -1 -1 -1 -1]
 [ 1  1  1 -1  1  1  1  1  1]
 [ 1  1 -1  1 -1 -1 -1 -1 -1]
 [ 1  1 -1  1 -1 -1 -1 -1 -1]
 [ 1  1  1  1 -1 -1 -1 -1  1]
 [ 1  1 -1 -1 -1 -1  1  1  1]
 [ 1 -1 -1 -1 -1 -1  1  1  1]
 [ 1  1  1 -1 -1 -1  1  1 -1]]
Correlated [[ 1  1 -1  1 -1 -1 -1 -1  1]
 [ 1  1 -1 -1 -1 -1 -1 -1 -1]
 [ 1  1 -1 -1 -1  1  1  1  1]
 [-1 -1 -1 -1 -1 -1  1  1  1]
 [ 1 -1 -1 -1 -1  1  1  1  1]
 [-1 -1 -1 -1 -1  1  1  1  1]
 [-1 -1 -1 -1 -1  1  1 -1 -1]
 [-1 -1 -1 -1 -1 -1  1  1  1]
 [-1 -1  1 -1 -1 -1 -1 -1  1]]


In [0]:
# Parameters
num_hidden_layers = 1
out_channels = 1
num_workers = 15
run_mode = "frozen_convolution_no_center_relu" # sys.argv[1]
n_loops = 3000
save_loop = min(n_loops, 10)

In [0]:
def init_model_and_train(hidden_size, batch_size, train_size, n_epochs, lr, weight_decay,
            betas0, betas1, seed):
    # Parameters
    num_hidden_layers = 1
    out_channels = 1


    if run_mode == "unfrozen_convolution_relu":
        model = supervised_convnet.SupervisedConvNet(filter_size = 3, square_size = 3, \
                hidden_size = hidden_size, out_channels = out_channels,
                first_activation = "tanh", activation_func = "relu",
                num_hidden_layers = num_hidden_layers, seed = seed)
        results = train.trainer(model = model, batch_size = batch_size, train_size = train_size, n_epochs = n_epochs, lr = lr,
                    weight_decay = weight_decay,
                    betas0 = 1-betas0, betas1 = 1-betas1)
    elif run_mode == "frozen_convolution_no_center_relu":
        model = frozen.SupervisedConvNet(filter_size = 3, square_size = 3, \
                hidden_size = hidden_size, out_channels = out_channels,
                center = "omit", first_activation = "tanh",
                activation_func = "relu", num_hidden_layers = num_hidden_layers)
        results = train.trainer(model = model, batch_size = batch_size, train_size = train_size, n_epochs = n_epochs, lr = lr,
                    weight_decay = weight_decay,
                    betas0 = 1-betas0, betas1 = 1-betas1)
    elif run_mode == "frozen_convolution_pretrained_relu":
        model = frozen.SupervisedConvNet(filter_size = 3, square_size = 3, \
                hidden_size = hidden_size, out_channels = out_channels,
                center = "pre_trained", first_activation = "tanh",
                activation_func = "relu", num_hidden_layers = num_hidden_layers)
        results = train.trainer(model = model, batch_size = batch_size, train_size = train_size, n_epochs = n_epochs, lr = lr,
                    weight_decay = weight_decay,
                    betas0 = 1-betas0, betas1 = 1-betas1)
    elif run_mode == "unfrozen_convolution_2_channels":
        out_channels = 2
        model = supervised_convnet.SupervisedConvNet(filter_size = 3, square_size = 3,
                hidden_size = hidden_size, out_channels = out_channels,
                first_activation = "tanh", activation_func = "relu",
                num_hidden_layers = num_hidden_layers, seed = seed)
        results = train.trainer(model = model, batch_size = batch_size, train_size = train_size, n_epochs = n_epochs, lr = lr,
                    weight_decay = weight_decay,
                    betas0 = 1-betas0, betas1 = 1-betas1)
    return (results[0])



def train_evaluate(parameterization):
    # parameters
    batch_size = parameterization["batch_size"]
    train_size = parameterization["train_size"]
    n_epochs = parameterization["n_epochs"]
    lr = parameterization["lr"]
    weight_decay = parameterization["weight_decay"]
    betas0 = parameterization["betas0"]
    betas1 = parameterization["betas1"]
    hidden_size = 10

    results = []
    for seed in range(num_workers):
        results.append(init_model_and_train(hidden_size, batch_size, train_size,
        n_epochs, lr, weight_decay, betas0, betas1,
        time.time() + seed))

    print ("results", results)
    mean = np.mean(results)
    SEM = np.std(results)/np.sqrt(num_workers)
    # pool.close() # no more tasks
    # pool.join()  # wrap up current tasks
    return {"objective": (mean, SEM)}



In [0]:
%%capture

# Initialize client
ax_client = AxClient()
try:
    with open(f"/content/drive/My Drive/Year 4: Synthesis/NS162: Statistical Mechanics/Renormalization Research Project/renormalization/supervised_convnet/t_2.269/3x3/colab/hyperparameters_{run_mode}.pl", "rb") as handle:
        hyper = pickle.load(handle)
    v = hyper["axclient"].copy()
    ax_client = ax_client.from_json_snapshot(v)
except:
    ax_client.create_experiment(
        parameters=[
            {
              "name": "batch_size",
              "type": "range",
              "bounds": [1, 5000],
              "value_type": "int"
            },
            {
              "name": "train_size",
              "type": "range",
              "bounds": [100, 5000],
              "value_type": "int"
            },
            {
              "name": "n_epochs",
              "type": "range",
              "bounds": [50, 250],
              "value_type": "int"
            },
            {
              "name": "lr",
              "type": "range",
              "bounds": [1e-4, 1],
              "value_type": "float",
              "log_scale": True
            },
            {
              "name": "weight_decay",
              "type": "range",
              "bounds": [1e-5, 2e-1],
              "value_type": "float",
              "log_scale": True
            },
            {
              "name": "betas0",
              "type": "range",
              "bounds": [1e-5, 2e-1],
              "value_type": "float",
              "log_scale": True
            },
            {
              "name": "betas1",
              "type": "range",
              "bounds": [1e-5, 2e-1],
              "value_type": "float",
              "log_scale": True
            }
        ],
        parameter_constraints=["0.02 * train_size + -1 * batch_size <= 0", "train_size >= batch_size"],
        minimize=False,
        objective_name="objective",
        outcome_constraints=None,
        name="Test"
    )

# print ("axclient",ax_client.experiment.trials )
# for loop in range(n_loops):
for loop in range(n_loops):
    print(f"Running trial {loop}/{n_loops}...")
    parameters, trial_index = ax_client.get_next_trial()
    print("trial_index", trial_index)
    time.sleep(2)
#     parameters["n_epochs"] = 5
     # Local evaluation here can be replaced with deployment to external system.
    ax_client.complete_trial(trial_index=trial_index, raw_data=train_evaluate(parameters))
    print("Best params", ax_client.get_best_parameters())
    # periodic save
    if loop % save_loop == (save_loop - 1):
        optim_result = ax_client.get_best_parameters()
        # print("best_parameters", optim_result)
        # print("was I saved?", ax._save_experiment_and_generation_strategy_if_possible())
        hyper = {}
        hyper["best_params"] = optim_result
        hyper["axclient"] = ax_client.to_json_snapshot()
        # print("optim_result", optim_result)
        with open(f"/content/drive/My Drive/Year 4: Synthesis/NS162: Statistical Mechanics/Renormalization Research Project/renormalization/supervised_convnet/t_2.269/3x3/colab/hyperparameters_{run_mode}.pl", "wb") as handle:
            pickle.dump(hyper, handle, protocol = pickle.HIGHEST_PROTOCOL)


In [0]:
i = 0 

In [0]:
train.__file__

'/content/drive/My Drive/Year 4: Synthesis/NS162: Statistical Mechanics/Renormalization Research Project/renormalization/supervised_convnet/t_2.269/3x3/train.py'

In [0]:
open(f"/content/drive/My Drive/Year 4: Synthesis/NS162: Statistical Mechanics/Renormalization Research Project/renormalization/supervised_convnet/t_2.269/colab/hyperparameters_{run_mode}.pl", "wb")


FileNotFoundError: ignored

In [0]:
open(f"/content/drive/My Drive/Year 4: Synthesis/NS162: Statistical Mechanics/Renormalization Research Project/renormalization/supervised_convnet/t_2.269/hyperparameters_{run_mode}.pl", "wb")

<_io.BufferedWriter name='/content/drive/My Drive/Year 4: Synthesis/NS162: Statistical Mechanics/Renormalization Research Project/renormalization/supervised_convnet/t_2.269/hyperparameters_unfrozen_convolution_relu.pl'>

In [0]:
with open(f"/content/drive/My Drive/Year 4: Synthesis/NS162: Statistical Mechanics/Renormalization Research Project/renormalization/supervised_convnet/t_2.269/hyperparameters_{run_mode}.pl", "wb") as handle:
    pickle.dump(hyper, handle, protocol = pickle.HIGHEST_PROTOCOL)

In [0]:
!ls /content/drive/My\ Drive/Year\ 4:\ Synthesis/NS162:\ Statistical\ Mechanics/Renormalization\ Research\ Project/renormalization/supervised_convnet/t_2.269/

 3x3	        generate_uncorrelated_data.py		       runs
 81x81	        hyperparameters_unfrozen_convolution_relu.pl
'9x9->3x3.pt'   ising81x81_temp2.269.npy
