In [1]:
# 

# !pip install -U --target=/usr/local/lib/python3.6/dist-packages git+https://github.com/pytorch/botorch.git

# !pip install -U -q torch==1.2.0 torchvision

# !pip install -U scikit-learn
# !pip install -U --target=/usr/local/lib/python3.6/dist-packages git+https://github.com/anhhuyalex/Ax.git
  
!pip install -U --target=/usr/local/lib/python3.6/dist-packages git+https://github.com/anhhuyalex/Ax.git
  
%cd /content
# %cd /usr/local/lib/python3.6/dist-packages
!rm -rf botorch
%cd /content
!git clone https://github.com/pytorch/botorch.git
%cd botorch
!pip install .

!pip install sqlalchemy

  Cloning https://github.com/anhhuyalex/Ax.git to /tmp/pip-req-build-keur6kd_
  Running command git clone -q https://github.com/anhhuyalex/Ax.git /tmp/pip-req-build-keur6kd_
     |████████████████████████████████| 174kB 8.1MB/s 
     |████████████████████████████████| 133kB 59.1MB/s 
     |████████████████████████████████| 10.5MB 72.5MB/s 
     |████████████████████████████████| 25.2MB 47.7MB/s 
     |████████████████████████████████| 7.1MB 47.6MB/s 
     |████████████████████████████████| 215kB 52.1MB/s 
     |████████████████████████████████| 748.9MB 29kB/s 
     |████████████████████████████████| 20.4MB 42.9MB/s 
     |████████████████████████████████| 235kB 64.7MB/s 
     |████████████████████████████████| 512kB 58.5MB/s 
     |████████████████████████████████| 6.7MB 26.5MB/s 
     |████████████████████████████████| 286kB 43.7MB/s 
  Created wheel for ax-platform: filename=ax_platform-0.1.4-cp36-cp36m-linux_x86_64.whl size=918248 sha256=02f3d8a48adefbc52dd6118e1849605126377d94b6d2f

/content
/content
Cloning into 'botorch'...
remote: Enumerating objects: 253, done.
remote: Counting objects: 100% (253/253), done.
remote: Compressing objects: 100% (176/176), done.
remote: Total 5949 (delta 100), reused 124 (delta 39), pack-reused 5696
Receiving objects: 100% (5949/5949), 10.53 MiB | 13.33 MiB/s, done.
Resolving deltas: 100% (3798/3798), done.
/content/botorch
Processing /content/botorch
  Created wheel for botorch: filename=botorch-0.1.3-cp36-none-any.whl size=175135 sha256=ac1bd503f067b35a867aecd72a2f4c9070f96f40eaa3c53f2c2653b1fbe4b9c8
  Stored in directory: /tmp/pip-ephem-wheel-cache-0wi824vx/wheels/d8/0e/3f/502176509633fec729eabc1a42e465b3603faf0c30b4782f33
Successfully built botorch
  Found existing installation: botorch 0.1.3
    Uninstalling botorch-0.1.3:
      Successfully uninstalled botorch-0.1.3


  Cloning https://github.com/pytorch/botorch.git to /tmp/pip-req-build-9kwtgry5
  Running command git clone -q https://github.com/pytorch/botorch.git /tmp/pip-req-build-9kwtgry5
  Using cached https://files.pythonhosted.org/packages/30/57/d5cceb0799c06733eefce80c395459f28970ebb9e896846ce96ab579a3f1/torch-1.2.0-cp36-cp36m-manylinux1_x86_64.whl
  Using cached https://files.pythonhosted.org/packages/29/50/a552a5aff252ae915f522e44642bb49a7b7b31677f9580cfd11bcc869976/scipy-1.3.1-cp36-cp36m-manylinux1_x86_64.whl
  Using cached https://files.pythonhosted.org/packages/75/92/57179ed45307ec6179e344231c47da7f3f3da9e2eee5c8ab506bd279ce4e/numpy-1.17.1-cp36-cp36m-manylinux1_x86_64.whl
  Created wheel for botorch: filename=botorch-0.1.3-cp36-none-any.whl size=175126 sha256=154fde2c7ac78b7be391d0b23e120d695155142afdc5c7a9e7b725be7ad598f5
  Stored in directory: /tmp/pip-ephem-wheel-cache-my6avjjg/wheels/82/70/31/16688bea51fa7ff1a0100a484854a6c2a9663fde3055aa478a
Successfully built botorch
ERROR: google

In [0]:

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

In [0]:
%cd /content/
!git clone https://github.com/anhhuyalex/renormalization.git
!cp /content/drive/My\ Drive/Year\ 4\:\ Synthesis/NS162\:\ Statistical\ Mechanics/Renormalization\ Research\ Project/renormalization/supervised_convnet/t_2.269/3x3/ising81x81_temp2.269_uncorrelated9x9.npy /content/renormalization/supervised_convnet/t_2.269/3x3
!cp /content/drive/My\ Drive/Year\ 4\:\ Synthesis/NS162\:\ Statistical\ Mechanics/Renormalization\ Research\ Project/renormalization/supervised_convnet/t_2.269/ising81x81_temp2.269.npy /content/renormalization/supervised_convnet/t_2.269      

/content
Cloning into 'renormalization'...
remote: Enumerating objects: 236, done.
remote: Counting objects: 100% (236/236), done.
remote: Compressing objects: 100% (135/135), done.
remote: Total 236 (delta 131), reused 190 (delta 85), pack-reused 0
Receiving objects: 100% (236/236), 546.02 KiB | 583.00 KiB/s, done.
Resolving deltas: 100% (131/131), done.


In [0]:
%cd /content/renormalization/supervised_convnet/t_2.269/3x3
import torch
import numpy as np
import pickle
import multiprocessing as mp

from ax import RangeParameter, ParameterType
from ax.service.ax_client import AxClient
from ax.plot.contour import plot_contour
from ax.plot.trace import optimization_trace_single_method
from ax.service.managed_loop import optimize
from ax.utils.notebook.plotting import render, init_notebook_plotting

import sys
import time
sys.path.insert(0, "../../")
import supervised_convnet
import train, frozen

/content/renormalization/supervised_convnet/t_2.269/3x3
Uncorrelated [[ 1  1  1 -1 -1 -1  1 -1 -1]
 [ 1  1  1 -1 -1 -1 -1 -1 -1]
 [ 1  1  1 -1  1  1  1  1  1]
 [ 1  1 -1  1 -1 -1 -1 -1 -1]
 [ 1  1 -1  1 -1 -1 -1 -1 -1]
 [ 1  1  1  1 -1 -1 -1 -1  1]
 [ 1  1 -1 -1 -1 -1  1  1  1]
 [ 1 -1 -1 -1 -1 -1  1  1  1]
 [ 1  1  1 -1 -1 -1  1  1 -1]]
Correlated [[ 1  1 -1  1 -1 -1 -1 -1  1]
 [ 1  1 -1 -1 -1 -1 -1 -1 -1]
 [ 1  1 -1 -1 -1  1  1  1  1]
 [-1 -1 -1 -1 -1 -1  1  1  1]
 [ 1 -1 -1 -1 -1  1  1  1  1]
 [-1 -1 -1 -1 -1  1  1  1  1]
 [-1 -1 -1 -1 -1  1  1 -1 -1]
 [-1 -1 -1 -1 -1 -1  1  1  1]
 [-1 -1  1 -1 -1 -1 -1 -1  1]]


In [0]:
# Parameters
num_hidden_layers = 1
out_channels = 1
weight = 0.02
num_workers = 4

# Initialize client
ax = AxClient()

In [0]:
def init_model_and_train(hidden_size, batch_size, train_size, n_epochs, lr, weight_decay,
            betas0, betas1, seed, output):
    model = supervised_convnet.SupervisedConvNet(filter_size = 3, square_size = 3, \
            hidden_size = hidden_size, out_channels = out_channels,
            first_activation = "tanh", activation_func = "relu",
            num_hidden_layers = num_hidden_layers, seed = seed)
    results = train.trainer(model = model, batch_size = batch_size, train_size = train_size, n_epochs = n_epochs, lr = lr,
                weight_decay = weight_decay,
                betas0 = 1-betas0, betas1 = 1-betas1)
    output.put(results)

def start_process():
    print ('Starting', mp.current_process().name)

# def train_evaluate(parameterization):
#     # parameters
#     batch_size = parameterization["batch_size"]
#     train_size = parameterization["train_size"]
#     n_epochs = parameterization["n_epochs"]
#     lr = parameterization["lr"]
#     weight_decay = parameterization["weight_decay"]
#     betas0 = parameterization["betas0"]
#     betas1 = parameterization["betas1"]
#     hidden_size = 10
#
#
#     output = []
#     with mp.Pool(processes=num_workers, initializer=start_process) as pool:
#     # accuracy = train.trainer(model = model, batch_size = batch_size, train_size = train_size, n_epochs = n_epochs, lr = lr,
#     #             weight_decay = weight_decay,
#     #             betas0 = 1-betas0, betas1 = 0.99)[0]
#     # results = [pool.apply(train.trainer, {"model" : model, "batch_size" : batch_size,
#     #             "train_size" : train_size, "n_epochs" : n_epochs, "lr" : lr,
#     #             "weight_decay" : weight_decay,
#     #             "betas0" : 1-betas0, "betas1" : 0.99}) for x in range(5)]
#         iterable = [(hidden_size, batch_size, train_size,
#                     n_epochs, lr, weight_decay, betas0, betas1, time.time() + seed) for seed in range(num_workers)]
#         print("iterable", iterable)
#         output = pool.starmap(init_model_and_train, iterable)
#     pool.join()
#     output = [result[0] for result in output]
#     print(output)
#     mean = np.mean(output)
#     SEM = np.std(output)/np.sqrt(4)
#     # pool.close() # no more tasks
#     # pool.join()  # wrap up current tasks
#     return mean, SEM


def train_evaluate(parameterization):
    # parameters
    batch_size = parameterization["batch_size"]
    train_size = parameterization["train_size"]
    n_epochs = parameterization["n_epochs"]
    lr = parameterization["lr"]
    weight_decay = parameterization["weight_decay"]
    betas0 = parameterization["betas0"]
    betas1 = parameterization["betas1"]
    hidden_size = 10

    # Define an output queue
    output = mp.Queue()

    # Setup a list of processes that we want to run
    processes = [mp.Process(target=init_model_and_train, args=(
                    hidden_size, batch_size, train_size,
                    n_epochs, lr, weight_decay, betas0, betas1,
                    time.time() + seed, output
                )) for seed in range(num_workers)]

    # Run processes
    for p in processes:
        p.start()

    # Exit the completed processes
    for p in processes:
        p.join()

    # Get process results from the output queue
    results = [output.get() for p in processes]
    results = [res[0] for res in results]
    mean = np.mean(results)
    SEM = np.std(results)/np.sqrt(4)
    # pool.close() # no more tasks
    # pool.join()  # wrap up current tasks
    return mean, SEM


ax.create_experiment(
    parameters=[
        {
          "name": "batch_size",
          "type": "range",
          "bounds": [1, 5000],
          "value_type": "int"
        },
        {
          "name": "train_size",
          "type": "range",
          "bounds": [100, 5000],
          "value_type": "int"
        },
        {
          "name": "n_epochs",
          "type": "range",
          "bounds": [50, 250],
          "value_type": "int"
        },
        {
          "name": "lr",
          "type": "range",
          "bounds": [1e-4, 1],
          "value_type": "float",
          "log_scale": True
        },
        {
          "name": "weight_decay",
          "type": "range",
          "bounds": [1e-5, 2e-1],
          "value_type": "float",
          "log_scale": True
        },
        {
          "name": "betas0",
          "type": "range",
          "bounds": [1e-5, 2e-1],
          "value_type": "float",
          "log_scale": True
        },
        {
          "name": "betas1",
          "type": "range",
          "bounds": [1e-5, 2e-1],
          "value_type": "float",
          "log_scale": True
        }
    ],
    parameter_constraints=["0.02 * n_epochs + -1 * batch_size <= 0"],
    minimize=False,
    outcome_constraints=None,
    name="Test"
)

[INFO 08-30 05:22:13] ax.service.utils.dispatch: Using Bayesian Optimization generation strategy: GenerationStrategy(name='Sobol+GPEI', steps=[Sobol for 7 arms, GPEI for subsequent arms], generated 0 arm(s) so far). Iterations after 7 will take longer to generate due to model-fitting.


In [0]:
for i in range(1):
    print(f"Running trial {i+1}/30...")
    parameters, trial_index = ax.get_next_trial()
    print(parameters)
     # Local evaluation here can be replaced with deployment to external system.
#     ax.complete_trial(trial_index=trial_index, raw_data=train_evaluate(parameters))
train_evaluate(parameters)
# best_parameters, values = ax.get_best_parameters()
# print("best_parameters", best_parameters)

# with open("hyperparameters.pl", "wb") as handle:
#     pickle.dump(optim_result, handle, protocol = pickle.HIGHEST_PROTOCOL)

Running trial 1/30...
{'batch_size': 1356, 'train_size': 4860, 'n_epochs': 238, 'lr': 0.905589446280529, 'weight_decay': 0.1603220224791051, 'betas0': 0.0003864157009784237, 'betas1': 0.003227154379380984}
Testing out: 
batch_size:  1356
train_size:  4860
Testing out: 
n_epochs:  238
lr:  0.905589446280529
batch_size:  1356
train_size:  4860
Testing out: 
weight_decay:  0.1603220224791051
Testing out: 
batch_size:  1356
betas0:  0.9996135842990216
n_epochs:  238
betas1:  0.996772845620619
lr:  0.905589446280529
weight_decay:  0.1603220224791051
hidden_size:  10
betas0:  0.9996135842990216
betas1:  0.996772845620619
hidden_size:  10
batch_size:  1356
conv1.weight tensor([[[[ 0.2455, -0.0727,  0.2083],
          [ 0.0231, -0.0938,  0.1609],
          [-0.2284, -0.0532, -0.2396]]]])train_size:  4860
train_size:  4860
n_epochs:  238
lr:  0.905589446280529
weight_decay:  0.1603220224791051
betas0:  0.9996135842990216
betas1:  0.996772845620619
conv1.weight tensor([[[[-0.2317, -0.0256,  0.29

/bin/bash: killall: command not found


In [0]:
train.__file__

'/content/drive/My Drive/Year 4: Synthesis/NS162: Statistical Mechanics/Renormalization Research Project/renormalization/supervised_convnet/t_2.269/3x3/train.py'