In [1]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
# !kill -9 -1
# memory footprint support libraries/code
!ln -sf /opt/bin/nvidia-smi /usr/bin/nvidia-smi
!pip install gputil
!pip install psutil
!pip install humanize
import psutil
import humanize
import os
import GPUtil as GPU
GPUs = GPU.getGPUs()
# XXX: only one GPU on Colab and isn’t guaranteed
# gpu = GPUs[0]
# def printm():
#  process = psutil.Process(os.getpid())
#  print("Gen RAM Free: " + humanize.naturalsize( psutil.virtual_memory().available ), " | Proc size: " + humanize.naturalsize( process.memory_info().rss))
#  print("GPU RAM Free: {0:.0f}MB | Used: {1:.0f}MB | Util {2:3.0f}% | Total {3:.0f}MB".format(gpu.memoryFree, gpu.memoryUsed, gpu.memoryUtil*100, gpu.memoryTotal))
# printm()



# !pip install -U --target=/usr/local/lib/python3.6/dist-packages git+https://github.com/pytorch/botorch.git

# !pip install -U -q torch==1.2.0 torchvision

# !pip install -U scikit-learn
# !pip install -U --target=/usr/local/lib/python3.6/dist-packages git+https://github.com/anhhuyalex/Ax.git
  
!pip install -U --target=/usr/local/lib/python3.6/dist-packages git+https://github.com/anhhuyalex/Ax.git
  
  
%cd /content
# %cd /usr/local/lib/python3.6/dist-packages
!rm -rf botorch
%cd /content
!git clone https://github.com/pytorch/botorch.git
%cd botorch
!pip install .

!pip install sqlalchemy
!pip install setproctitle
!pip install ray[rllib]  # also recommended: ray[debug]
!pip uninstall -y pyarrow

  Created wheel for gputil: filename=GPUtil-1.4.0-cp36-none-any.whl size=7410 sha256=42a3098d1ba1a54afd4110e763361dafc3956679b3361c173c2c5ce2e77a58f0
  Stored in directory: /root/.cache/pip/wheels/3d/77/07/80562de4bb0786e5ea186911a2c831fdd0018bda69beab71fd
Successfully built gputil
  Cloning https://github.com/anhhuyalex/Ax.git to /tmp/pip-req-build-29mki2e7
  Running command git clone -q https://github.com/anhhuyalex/Ax.git /tmp/pip-req-build-29mki2e7
     |████████████████████████████████| 174kB 2.7MB/s 
     |████████████████████████████████| 133kB 40.2MB/s 
     |████████████████████████████████| 10.5MB 21.6MB/s 
     |████████████████████████████████| 25.2MB 34.4MB/s 
     |████████████████████████████████| 7.1MB 25.2MB/s 
     |████████████████████████████████| 748.9MB 19kB/s 
     |████████████████████████████████| 215kB 36.8MB/s 
     |████████████████████████████████| 512kB 41.0MB/s 
     |████████████████████████████████| 20.4MB 27.0MB/s 
     |███████████████████████████████

/content
/content
Cloning into 'botorch'...
remote: Enumerating objects: 189, done.
remote: Counting objects: 100% (189/189), done.
remote: Compressing objects: 100% (111/111), done.
remote: Total 6228 (delta 68), reused 101 (delta 3), pack-reused 6039
Receiving objects: 100% (6228/6228), 10.82 MiB | 7.12 MiB/s, done.
Resolving deltas: 100% (4022/4022), done.
/content/botorch
Processing /content/botorch
  Created wheel for botorch: filename=botorch-0.1.3-cp36-none-any.whl size=172334 sha256=c37bfbbf08af014b6726834f0ca39916ce981b47f3cb4ef52714785edb888306
  Stored in directory: /tmp/pip-ephem-wheel-cache-ek0qykts/wheels/d8/0e/3f/502176509633fec729eabc1a42e465b3603faf0c30b4782f33
Successfully built botorch
  Found existing installation: botorch 0.1.3
    Uninstalling botorch-0.1.3:
      Successfully uninstalled botorch-0.1.3
  Created wheel for setproctitle: filename=setproctitle-1.1.10-cp36-cp36m-linux_x86_64.whl size=33933 sha256=7cfd60269d5295816e1eb4eec172f62d231f090cd624b65fea810da

Uninstalling pyarrow-0.14.1:
  Successfully uninstalled pyarrow-0.14.1


In [1]:
%cd /content/drive/My\ Drive/Year\ 4\:\ Synthesis/NS162\:\ Statistical\ Mechanics/Renormalization\ Research\ Project/renormalization/supervised_convnet/t_2.269/81x81
import torch
import numpy as np
import pickle
import ray

from ax import RangeParameter, ParameterType
from ax.service.ax_client import AxClient
from ax.plot.contour import plot_contour
from ax.plot.trace import optimization_trace_single_method
from ax.service.managed_loop import optimize
from ax.utils.notebook.plotting import render, init_notebook_plotting

import sys
import time
# sys.path.insert(0, "../../")
import supervised_convnet
import train

/content/drive/My Drive/Year 4: Synthesis/NS162: Statistical Mechanics/Renormalization Research Project/renormalization/supervised_convnet/t_2.269/81x81


/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning:

Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.

/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning:

Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.

/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning:

Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.

/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning:

Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '

Uncorrelated [[ 1  1  1  1  1  1 -1 -1 -1 -1 -1  1  1  1 -1 -1  1 -1  1  1]
 [ 1  1  1  1  1  1 -1 -1 -1 -1 -1  1  1  1 -1  1  1  1  1  1]
 [ 1  1  1  1  1  1 -1 -1 -1  1 -1 -1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1 -1  1  1 -1 -1 -1 -1 -1 -1 -1  1  1 -1 -1]
 [ 1  1  1  1  1  1  1  1  1 -1 -1  1 -1 -1 -1 -1  1  1 -1 -1]
 [ 1  1  1  1  1  1  1  1  1 -1 -1  1 -1  1 -1 -1 -1 -1 -1 -1]
 [ 1 -1 -1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1  1  1 -1 -1 -1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1  1  1  1  1 -1 -1 -1  1  1  1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1  1  1  1 -1 -1 -1  1  1  1  1 -1]
 [-1  1 -1 -1 -1 -1 -1 -1 -1 -1  1  1 -1 -1 -1  1  1  1  1  1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1 -1  1  1  1  1 -1  1  1]
 [ 1  1  1  1  1  1 -1 -1 -1  1 -1  1 -1 -1 -1 -1 -1  1  1  1]
 [ 1  1  1  1  1  1 -1 -1 -1  1  1  1 -1 -1  1 -1 -1 -1  1  1]
 [ 1  1  1  1  1  1 -1 -1 -1  1  1  1 -1 -1  1  1 -1 -1  1  1]
 [-1 -1 -1  1  1  1 -1 -1 -1  1  1  1  1  

In [0]:
# Parameters
num_hidden_layers = 1
num_conv_layers = 3
out_channels = 1
num_workers = 1
num_times = 1
run_mode = "multilayer_1channel"
n_loops = 3000
save_loop = min(n_loops, 2)
use_cuda = True

In [3]:
# Start Ray.
ray.init()
#ray.init(num_gpus=1)

# GPU for use in colab
def model_to_cuda(model):
    if use_cuda and torch.cuda.is_available():
        model = model.cuda()
    return model

# @ray.remote(num_gpus = 1/num_workers)
# @ray.remote
def init_model_and_train(hidden_size, batch_size, train_size, n_epochs, lr, weight_decay,
            betas0, betas1, seed, use_cuda):
    # Parameters
    num_hidden_layers = 1
    out_channels = 1


    if run_mode == "multilayer_1channel":
        model = supervised_convnet.MultiLayerConvNet(filter_size = 3, square_size = 3, \
                hidden_size = hidden_size, out_channels = out_channels,
                first_activation = "tanh", activation_func = "relu",
                num_hidden_layers = num_hidden_layers, num_conv_layers = num_conv_layers, seed = seed)
        model = model_to_cuda(model)
        results = train.trainer(model = model, batch_size = batch_size, train_size = train_size, n_epochs = n_epochs, lr = lr,
                    weight_decay = weight_decay,
                    betas0 = 1-betas0, betas1 = 1-betas1, use_cuda = use_cuda)
    return (results[0])



def train_evaluate(parameterization, use_cuda = use_cuda):
    # parameters
    batch_size = parameterization["batch_size"]
    train_size = parameterization["train_size"]
    n_epochs = parameterization["n_epochs"]
    lr = parameterization["lr"]
    weight_decay = parameterization["weight_decay"]
    betas0 = parameterization["betas0"]
    betas1 = parameterization["betas1"]
    hidden_size = 10
    use_cuda = use_cuda

    results = []
    # Start 4 tasks in parallel.
    for _ in range(num_times):
#         result_ids = []
        for seed in range(num_workers):
            result_ids = (init_model_and_train(hidden_size, batch_size, train_size,
            n_epochs, lr, weight_decay, betas0, betas1,
            time.time() + seed, use_cuda))

        # Wait for the tasks to complete and retrieve the results.
        # With at least 4 cores, this will take 1 second.
        results.append(result_ids)

    # results = []
    # for seed in range(num_workers):
    #     results.append(init_model_and_train(hidden_size, batch_size, train_size,
    #     n_epochs, lr, weight_decay, betas0, betas1,
    #     time.time() + seed))

    print ("results", results)
    mean = np.mean(results)
    SEM = np.std(results)/np.sqrt(len(results))
    # pool.close() # no more tasks
    # pool.join()  # wrap up current tasks
    return {"objective": (mean, SEM)}

2019-09-15 11:34:05,557	INFO resource_spec.py:205 -- Starting Ray with 3.47 GiB memory available for workers and up to 1.74 GiB for objects. You can adjust these settings with ray.remote(memory=<bytes>, object_store_memory=<bytes>).


In [4]:
# %%capture
# Initialize client
ax_client = AxClient()
try:
    with open(f"/content/drive/My Drive/Year 4: Synthesis/NS162: Statistical Mechanics/Renormalization Research Project/renormalization/supervised_convnet/t_2.269/81x81/colab/hyperparameters_{run_mode}.pl", "rb") as handle:
        hyper = pickle.load(handle)
    v = hyper["axclient"].copy()
    ax_client = ax_client.from_json_snapshot(v)
except:
    ax_client.create_experiment(
        parameters=[
            {
              "name": "batch_size",
              "type": "range",
              "bounds": [1, 5000],
              "value_type": "int"
            },
            {
              "name": "train_size",
              "type": "range",
              "bounds": [100, 5000],
              "value_type": "int"
            },
            {
              "name": "n_epochs",
              "type": "range",
              "bounds": [50, 250],
              "value_type": "int"
            },
            {
              "name": "lr",
              "type": "range",
              "bounds": [1e-4, 1],
              "value_type": "float",
              "log_scale": True
            },
            {
              "name": "weight_decay",
              "type": "range",
              "bounds": [1e-6, 2e-1],
              "value_type": "float",
              "log_scale": True
            },
            {
              "name": "betas0",
              "type": "range",
              "bounds": [1e-5, 2e-1],
              "value_type": "float",
              "log_scale": True
            },
            {
              "name": "betas1",
              "type": "range",
              "bounds": [1e-5, 2e-1],
              "value_type": "float",
              "log_scale": True
            }
        ],
        parameter_constraints=["0.02 * train_size + -1 * batch_size <= 0", "train_size >= batch_size"],
        minimize=False,
        objective_name="objective",
        outcome_constraints=None,
        name="Test"
    )

# print ("axclient",ax_client.experiment.trials )
# for loop in range(n_loops):
for loop in range(n_loops):
    print(f"Running trial {loop}/{n_loops}...")
    parameters, trial_index = ax_client.get_next_trial()
    print("trial_index", trial_index)
#     time.sleep(2)
    # parameters["n_epochs"] = 5
     # Local evaluation here can be replaced with deployment to external system.
    ax_client.complete_trial(trial_index=trial_index, raw_data=train_evaluate(parameters))
    print("Best params", ax_client.get_best_parameters())
    # periodic save
    if loop % save_loop == (save_loop - 1):
        optim_result = ax_client.get_best_parameters()
        # print("best_parameters", optim_result)
        # print("was I saved?", ax._save_experiment_and_generation_strategy_if_possible())
        hyper = {}
        hyper["best_params"] = optim_result
        hyper["axclient"] = ax_client.to_json_snapshot()
        # print("optim_result", optim_result)
        with open(f"/content/drive/My Drive/Year 4: Synthesis/NS162: Statistical Mechanics/Renormalization Research Project/renormalization/supervised_convnet/t_2.269/81x81/colab/hyperparameters_{run_mode}.pl", "wb") as handle:
            pickle.dump(hyper, handle, protocol = pickle.HIGHEST_PROTOCOL)




[INFO 09-15 11:34:08] ax.service.utils.dispatch: Using Bayesian Optimization generation strategy: GenerationStrategy(name='Sobol+GPEI', steps=[Sobol for 7 arms, GPEI for subsequent arms], generated 0 arm(s) so far). Iterations after 7 will take longer to generate due to model-fitting.


Running trial 0/3000...
trial_index 0
Testing out: 
batch_size:  333
train_size:  4507
n_epochs:  140
lr:  0.013129926378913864
weight_decay:  0.006548393637074118
betas0:  0.9882112065050164
betas1:  0.9999515587494343
hidden_size:  10
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 10
epoch 11
epoch 12
epoch 13
epoch 14
epoch 15
epoch 16
epoch 17
epoch 18
epoch 19
epoch 20
epoch 21
epoch 22
epoch 23
epoch 24
epoch 25
epoch 26
epoch 27
epoch 28
epoch 29
epoch 30
epoch 31
epoch 32
epoch 33
epoch 34
epoch 35
epoch 36
epoch 37
epoch 38
epoch 39
epoch 40
epoch 41
epoch 42
epoch 43
epoch 44
epoch 45
epoch 46
epoch 47
epoch 48
epoch 49
epoch 50
epoch 51
epoch 52
epoch 53
epoch 54
epoch 55
epoch 56
epoch 57
epoch 58
epoch 59
epoch 60
epoch 61
epoch 62
epoch 63
epoch 64
epoch 65
epoch 66
epoch 67
epoch 68
epoch 69
epoch 70
epoch 71
epoch 72
epoch 73
epoch 74
epoch 75
epoch 76
epoch 77
epoch 78
epoch 79
epoch 80
epoch 81
epoch 82
epoch 83
epoch 84
epoch 85
epoch 8

2019-09-15 12:55:35,041	ERROR import_thread.py:89 -- ImportThread: Connection closed by server.
2019-09-15 12:55:35,042	ERROR worker.py:1693 -- print_logs: Connection closed by server.
2019-09-15 12:55:35,044	ERROR worker.py:1793 -- listen_error_messages_raylet: Connection closed by server.


KeyboardInterrupt: ignored

In [5]:
ax_client.get_best_parameters()

({'batch_size': 534,
  'betas0': 0.009367812437484689,
  'betas1': 0.0011636320996308597,
  'lr': 0.18602018785651322,
  'n_epochs': 165,
  'train_size': 2459,
  'weight_decay': 0.0034972858295468723},
 ({'objective': 0.9984998292805287},
  {'objective': {'objective': 1.6641401663592304e-09}}))