In [0]:
!df -h
!cat /proc/cpuinfo
!cat /proc/meminfo

Filesystem      Size  Used Avail Use% Mounted on
overlay         359G   30G  311G   9% /
tmpfs            64M     0   64M   0% /dev
tmpfs           6.4G     0  6.4G   0% /sys/fs/cgroup
tmpfs           6.4G   12K  6.4G   1% /var/colab
/dev/sda1       365G   41G  325G  12% /opt/bin
shm             5.9G  4.0K  5.9G   1% /dev/shm
tmpfs           6.4G     0  6.4G   0% /proc/acpi
tmpfs           6.4G     0  6.4G   0% /proc/scsi
tmpfs           6.4G     0  6.4G   0% /sys/firmware
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0x1
cpu MHz		: 2199.998
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid

In [1]:
# !kill -9 -1
# memory footprint support libraries/code
!ln -sf /opt/bin/nvidia-smi /usr/bin/nvidia-smi
!pip install gputil
!pip install psutil
!pip install humanize
import psutil
import humanize
import os
import GPUtil as GPU
GPUs = GPU.getGPUs()
# XXX: only one GPU on Colab and isn’t guaranteed
# gpu = GPUs[0]
# def printm():
#  process = psutil.Process(os.getpid())
#  print("Gen RAM Free: " + humanize.naturalsize( psutil.virtual_memory().available ), " | Proc size: " + humanize.naturalsize( process.memory_info().rss))
#  print("GPU RAM Free: {0:.0f}MB | Used: {1:.0f}MB | Util {2:3.0f}% | Total {3:.0f}MB".format(gpu.memoryFree, gpu.memoryUsed, gpu.memoryUtil*100, gpu.memoryTotal))
# printm()



# !pip install -U --target=/usr/local/lib/python3.6/dist-packages git+https://github.com/pytorch/botorch.git

# !pip install -U -q torch==1.2.0 torchvision

# !pip install -U scikit-learn
# !pip install -U --target=/usr/local/lib/python3.6/dist-packages git+https://github.com/anhhuyalex/Ax.git
  
!pip install -U --target=/usr/local/lib/python3.6/dist-packages git+https://github.com/anhhuyalex/Ax.git
  
  
%cd /content
# %cd /usr/local/lib/python3.6/dist-packages
!rm -rf botorch
%cd /content
!git clone https://github.com/pytorch/botorch.git
%cd botorch
!pip install .

%cd /content
# %cd /usr/local/lib/python3.6/dist-packages
!rm -rf gpytorch
%cd /content
!git clone https://github.com/cornellius-gp/gpytorch.git
%cd gpytorch
!pip install .

!pip install sqlalchemy
!pip install setproctitle
!pip install ray[rllib]  # also recommended: ray[debug]
!pip uninstall -y pyarrow

  Created wheel for gputil: filename=GPUtil-1.4.0-cp36-none-any.whl size=7410 sha256=99a803be2a62666f1da1cf1f793844289f897b307823c24f42c69aae17fb3759
  Stored in directory: /root/.cache/pip/wheels/3d/77/07/80562de4bb0786e5ea186911a2c831fdd0018bda69beab71fd
Successfully built gputil
  Cloning https://github.com/anhhuyalex/Ax.git to /tmp/pip-req-build-i_uvuf5i
  Running command git clone -q https://github.com/anhhuyalex/Ax.git /tmp/pip-req-build-i_uvuf5i
     |████████████████████████████████| 174kB 2.8MB/s 
     |████████████████████████████████| 133kB 47.7MB/s 
     |████████████████████████████████| 10.5MB 49.1MB/s 
     |████████████████████████████████| 25.2MB 34.4MB/s 
     |████████████████████████████████| 7.1MB 29.5MB/s 
     |████████████████████████████████| 215kB 42.9MB/s 
     |████████████████████████████████| 773.1MB 31kB/s 
     |████████████████████████████████| 20.4MB 28.5MB/s 
     |████████████████████████████████| 235kB 41.4MB/s 
     |███████████████████████████████

/content
/content
Cloning into 'botorch'...
remote: Enumerating objects: 129, done.
remote: Counting objects: 100% (129/129), done.
remote: Compressing objects: 100% (88/88), done.
remote: Total 6912 (delta 40), reused 76 (delta 22), pack-reused 6783
Receiving objects: 100% (6912/6912), 11.13 MiB | 29.84 MiB/s, done.
Resolving deltas: 100% (4396/4396), done.
/content/botorch
Processing /content/botorch
  Created wheel for botorch: filename=botorch-0.1.4-cp36-none-any.whl size=180252 sha256=2086c5d412b319abc75b1a591f78a4272a33369a9abf5abdf5650958d60c85bd
  Stored in directory: /tmp/pip-ephem-wheel-cache-dnm9an0p/wheels/d8/0e/3f/502176509633fec729eabc1a42e465b3603faf0c30b4782f33
Successfully built botorch
  Found existing installation: botorch 0.1.4
    Uninstalling botorch-0.1.4:
      Successfully uninstalled botorch-0.1.4
/content
/content
Cloning into 'gpytorch'...
remote: Enumerating objects: 224, done.
remote: Counting objects: 100% (224/224), done.
remote: Compressing objects: 100

Uninstalling pyarrow-0.14.1:
  Successfully uninstalled pyarrow-0.14.1


In [2]:

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [1]:
%cd /content/drive/My\ Drive/Year\ 4\:\ Synthesis/NS162\:\ Statistical\ Mechanics/Renormalization\ Research\ Project/renormalization/supervised_convnet/t_2.269/layer_by_layer
import torch
import numpy as np
import pickle
import ray

from ax import RangeParameter, ParameterType
from ax.service.ax_client import AxClient
from ax.plot.contour import plot_contour
from ax.plot.trace import optimization_trace_single_method
from ax.service.managed_loop import optimize
from ax.utils.notebook.plotting import render, init_notebook_plotting

# import sys
import time
# sys.path.insert(0, "../../")
import supervised_convnet
import train#, frozen

/content/drive/My Drive/Year 4: Synthesis/NS162: Statistical Mechanics/Renormalization Research Project/renormalization/supervised_convnet/t_2.269/layer_by_layer
Uncorrelated [[ 0.32  0.54  0.37 -0.16  0.22  0.45 -0.19  0.22  0.28]
 [ 0.23  0.23  0.51 -0.37 -0.14 -0.06  0.48  0.18  0.5 ]
 [ 0.5   0.64  0.54 -0.56 -0.18 -0.06  0.39  0.42  0.51]
 [ 0.57  0.03 -0.02 -0.55 -0.25 -0.17  0.55  0.05  0.41]
 [ 0.38 -0.16  0.06 -0.36 -0.22 -0.44  0.31  0.53  0.6 ]
 [ 0.03 -0.01  0.33 -0.41 -0.19 -0.35  0.56  0.4   0.56]
 [-0.5  -0.47 -0.5   0.49  0.65  0.55  0.42  0.43 -0.43]
 [-0.26 -0.57 -0.39  0.15  0.6   0.48  0.54  0.55 -0.21]
 [-0.48 -0.58 -0.52  0.52  0.59 -0.22  0.33  0.2   0.46]]
Correlated [[ 0.07  0.53  0.51  0.63  0.61  0.6   0.59  0.57  0.4 ]
 [ 0.33  0.33  0.33  0.61  0.62  0.56  0.6   0.47  0.59]
 [ 0.51  0.64  0.57  0.61  0.54  0.46  0.23  0.23  0.53]
 [ 0.58  0.49  0.56  0.61  0.55  0.63  0.44 -0.1   0.54]
 [ 0.57  0.54  0.62  0.58  0.51  0.57  0.47  0.08  0.12]
 [ 0.57  0.57  

In [0]:
# Parameters
num_hidden_layers = 1
out_channels = 1
num_workers = 2
num_times = 1
run_mode = "unfrozen_convolution_relu9x9"
n_loops = 3000
save_loop = min(n_loops, 2)
use_cuda = True

In [3]:
# Start Ray.
ray.init()
#ray.init(num_gpus=1)

# GPU for use in colab
def model_to_cuda(model):
    if use_cuda and torch.cuda.is_available():
        model = model.cuda()
    return model

# @ray.remote(num_gpus = 1/num_workers)
@ray.remote
def init_model_and_train(hidden_size, batch_size, train_size, n_epochs, lr, weight_decay,
            betas0, betas1, seed, use_cuda):
    # Parameters
    num_hidden_layers = 1
    out_channels = 1


    if run_mode == "unfrozen_convolution_relu":
        model = supervised_convnet.SupervisedConvNet(filter_size = 3, square_size = 3, \
                hidden_size = hidden_size, out_channels = out_channels,
                first_activation = "tanh", activation_func = "relu",
                num_hidden_layers = num_hidden_layers, seed = seed)
        model = model_to_cuda(model)
        results = train.trainer(model = model, batch_size = batch_size, train_size = train_size, n_epochs = n_epochs, lr = lr,
                    weight_decay = weight_decay,
                    betas0 = 1-betas0, betas1 = 1-betas1, use_cuda = use_cuda)
    elif run_mode == "unfrozen_convolution_relu9x9":
        model = supervised_convnet.SupervisedConvNet(filter_size = 3, square_size = 3, \
                hidden_size = hidden_size, out_channels = out_channels,
                first_activation = "tanh", activation_func = "relu",
                num_hidden_layers = num_hidden_layers, seed = seed)
        model = model_to_cuda(model)
        results = train.trainer(model = model, batch_size = batch_size, train_size = train_size, n_epochs = n_epochs, lr = lr,
                    weight_decay = weight_decay,
                    betas0 = 1-betas0, betas1 = 1-betas1, use_cuda = use_cuda)
    elif run_mode == "frozen_convolution_no_center_relu":
        model = frozen.SupervisedConvNet(filter_size = 3, square_size = 3, \
                hidden_size = hidden_size, out_channels = out_channels,
                center = "omit", first_activation = "tanh",
                activation_func = "relu", num_hidden_layers = num_hidden_layers)
        model = model_to_cuda(model)
        results = train.trainer(model = model, batch_size = batch_size, train_size = train_size, n_epochs = n_epochs, lr = lr,
                    weight_decay = weight_decay,
                    betas0 = 1-betas0, betas1 = 1-betas1, use_cuda = use_cuda)
    elif run_mode == "frozen_convolution_pretrained_relu":
        model = frozen.SupervisedConvNet(filter_size = 3, square_size = 3, \
                hidden_size = hidden_size, out_channels = out_channels,
                center = "pre_trained", first_activation = "tanh",
                activation_func = "relu", num_hidden_layers = num_hidden_layers)
        model = model_to_cuda(model)
        results = train.trainer(model = model, batch_size = batch_size, train_size = train_size, n_epochs = n_epochs, lr = lr,
                    weight_decay = weight_decay,
                    betas0 = 1-betas0, betas1 = 1-betas1, use_cuda = use_cuda)
    elif run_mode == "unfrozen_convolution_2_channels":
        out_channels = 2
        model = supervised_convnet.SupervisedConvNet(filter_size = 3, square_size = 3,
                hidden_size = hidden_size, out_channels = out_channels,
                first_activation = "tanh", activation_func = "relu",
                num_hidden_layers = num_hidden_layers, seed = seed)
        model = model_to_cuda(model)
        results = train.trainer(model = model, batch_size = batch_size, train_size = train_size, n_epochs = n_epochs, lr = lr,
                    weight_decay = weight_decay,
                    betas0 = 1-betas0, betas1 = 1-betas1, use_cuda = use_cuda)
    return (results[0])



def train_evaluate(parameterization, use_cuda = use_cuda):
    # parameters
    batch_size = parameterization["batch_size"]
    train_size = parameterization["train_size"]
    n_epochs = parameterization["n_epochs"]
    lr = parameterization["lr"]
    weight_decay = parameterization["weight_decay"]
    betas0 = parameterization["betas0"]
    betas1 = parameterization["betas1"]
    hidden_size = 10
    use_cuda = use_cuda

    results = []
    # Start 4 tasks in parallel.
    for _ in range(num_times):
        result_ids = []
        for seed in range(num_workers):
            result_ids.append(init_model_and_train.remote(hidden_size, batch_size, train_size,
            n_epochs, lr, weight_decay, betas0, betas1,
            time.time() + seed, use_cuda))

        # Wait for the tasks to complete and retrieve the results.
        # With at least 4 cores, this will take 1 second.
        results.append(ray.get(result_ids))  # [0, 1, 2, 3]

    # results = []
    # for seed in range(num_workers):
    #     results.append(init_model_and_train(hidden_size, batch_size, train_size,
    #     n_epochs, lr, weight_decay, betas0, betas1,
    #     time.time() + seed))

    print ("results", results)
    mean = np.mean(results)
    SEM = np.std(results)/np.sqrt(len(results))
    # pool.close() # no more tasks
    # pool.join()  # wrap up current tasks
    return {"objective": (mean, SEM)}

2019-10-10 23:21:21,201	INFO resource_spec.py:205 -- Starting Ray with 4.49 GiB memory available for workers and up to 2.25 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).


In [0]:
%%capture
# Initialize client
ax_client = AxClient()
try:
    with open(f"/content/drive/My Drive/Year 4: Synthesis/NS162: Statistical Mechanics/Renormalization Research Project/renormalization/supervised_convnet/t_2.269/layer_by_layer/colab/hyperparameters_{run_mode}.pl", "rb") as handle:
        hyper = pickle.load(handle)
    v = hyper["axclient"].copy()
    ax_client = ax_client.from_json_snapshot(v)
except:
    ax_client.create_experiment(
        parameters=[
            {
              "name": "batch_size",
              "type": "range",
              "bounds": [1, 5000],
              "value_type": "int"
            },
            {
              "name": "train_size",
              "type": "range",
              "bounds": [100, 5000],
              "value_type": "int"
            },
            {
              "name": "n_epochs",
              "type": "range",
              "bounds": [50, 250],
              "value_type": "int"
            },
            {
              "name": "lr",
              "type": "range",
              "bounds": [1e-4, 1],
              "value_type": "float",
              "log_scale": True
            },
            {
              "name": "weight_decay",
              "type": "range",
              "bounds": [1e-5, 2e-1],
              "value_type": "float",
              "log_scale": True
            },
            {
              "name": "betas0",
              "type": "range",
              "bounds": [1e-5, 2e-1],
              "value_type": "float",
              "log_scale": True
            },
            {
              "name": "betas1",
              "type": "range",
              "bounds": [1e-5, 2e-1],
              "value_type": "float",
              "log_scale": True
            }
        ],
        parameter_constraints=["0.02 * train_size + -1 * batch_size <= 0", "train_size >= batch_size"],
        minimize=False,
        objective_name="objective",
        outcome_constraints=None,
        name="Test"
    )

# print ("axclient",ax_client.experiment.trials )
# for loop in range(n_loops):
for loop in range(n_loops):
    print(f"Running trial {loop}/{n_loops}...")
    parameters, trial_index = ax_client.get_next_trial()
    print("trial_index", trial_index)
#     time.sleep(2)
    # parameters["n_epochs"] = 5
     # Local evaluation here can be replaced with deployment to external system.
    ax_client.complete_trial(trial_index=trial_index, raw_data=train_evaluate(parameters))
    print("Best params", ax_client.get_best_parameters())
    # periodic save
    if loop % save_loop == (save_loop - 1):
        optim_result = ax_client.get_best_parameters()
        # print("best_parameters", optim_result)
        # print("was I saved?", ax._save_experiment_and_generation_strategy_if_possible())
        hyper = {}
        hyper["best_params"] = optim_result
        hyper["axclient"] = ax_client.to_json_snapshot()
        # print("optim_result", optim_result)
        with open(f"/content/drive/My Drive/Year 4: Synthesis/NS162: Statistical Mechanics/Renormalization Research Project/renormalization/supervised_convnet/t_2.269/layer_by_layer/colab/hyperparameters_{run_mode}.pl", "wb") as handle:
            pickle.dump(hyper, handle, protocol = pickle.HIGHEST_PROTOCOL)




[INFO 10-10 23:21:23] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 2 decimal points.
[INFO 10-10 23:21:23] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 2 decimal points.
[INFO 10-10 23:21:23] ax.service.ax_client: Generated new trial 2 with parameters {'batch_size': 1829, 'train_size': 3097, 'n_epochs': 117, 'lr': 0.09, 'weight_decay': 0.0, 'betas0': 0.01, 'betas1': 0.0}.
[INFO 10-10 23:21:39] ax.service.ax_client: Completed trial 2 with data: {'objective': (0.86, 0.01)}.
[INFO 10-10 23:21:39] ax.service.ax_client: Generated new trial 3 with parameters {'batch_size': 3371, 'train_size': 3805, 'n_epochs': 156, 'lr': 0.23, 'weight_decay': 0.0, 'betas0': 0.02, 'betas1': 0.0}.
[INFO 10-10 23:21:54] ax.service.ax_client

In [0]:
 i = 0

In [0]:
train.__file__

'/content/drive/My Drive/Year 4: Synthesis/NS162: Statistical Mechanics/Renormalization Research Project/renormalization/supervised_convnet/t_2.269/3x3/train.py'

In [0]:
open(f"/content/drive/My Drive/Year 4: Synthesis/NS162: Statistical Mechanics/Renormalization Research Project/renormalization/supervised_convnet/t_2.269/colab/hyperparameters_{run_mode}.pl", "wb")


FileNotFoundError: ignored

In [0]:
open(f"/content/drive/My Drive/Year 4: Synthesis/NS162: Statistical Mechanics/Renormalization Research Project/renormalization/supervised_convnet/t_2.269/hyperparameters_{run_mode}.pl", "wb")

<_io.BufferedWriter name='/content/drive/My Drive/Year 4: Synthesis/NS162: Statistical Mechanics/Renormalization Research Project/renormalization/supervised_convnet/t_2.269/hyperparameters_unfrozen_convolution_relu.pl'>

In [0]:
with open(f"/content/drive/My Drive/Year 4: Synthesis/NS162: Statistical Mechanics/Renormalization Research Project/renormalization/supervised_convnet/t_2.269/hyperparameters_{run_mode}.pl", "wb") as handle:
    pickle.dump(hyper, handle, protocol = pickle.HIGHEST_PROTOCOL)

In [0]:
!ls /content/drive/My\ Drive/Year\ 4:\ Synthesis/NS162:\ Statistical\ Mechanics/Renormalization\ Research\ Project/renormalization/supervised_convnet/t_2.269/

 3x3	        generate_uncorrelated_data.py		       runs
 81x81	        hyperparameters_unfrozen_convolution_relu.pl
'9x9->3x3.pt'   ising81x81_temp2.269.npy


In [0]:
i = 0